/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type WorkWithUsPage = {
  _id: string;
  _type: "workWithUsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroParagraphs?: Array<
    {
      _key: string;
    } & InternationalizedArrayText
  >;
  cvUploadCta?: InternationalizedArrayString;
  heroImage?: ImageWithAlt;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  };
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: InternationalizedArrayString;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type VolunteerPage = {
  _id: string;
  _type: "volunteerPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroParagraphs?: Array<
    {
      _key: string;
    } & InternationalizedArrayText
  >;
  highlights?: Array<
    {
      _key: string;
    } & IconCard
  >;
  closingParagraphs?: Array<
    {
      _key: string;
    } & InternationalizedArrayText
  >;
  applyCta?: CtaLink;
  heroImage?: ImageWithAlt;
  seo?: Seo;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: InternationalizedArrayString;
  href?: string;
  localizedHrefOverride?: InternationalizedArrayString;
};

export type SocialLinks = {
  _id: string;
  _type: "socialLinks";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  cvr?: string;
  website?: string;
  siteUrl?: string;
  defaultSeo?: Seo;
  announcementEnabled?: boolean;
  announcementText?: InternationalizedArrayString;
  announcementLink?: CtaLink;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & NavItem
  >;
  languageSwitcherLabel?: InternationalizedArrayString;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageKey?: "terms" | "privacy-policy" | "cookie-policy";
  title?: InternationalizedArrayString;
  subtitle?: InternationalizedArrayText;
  lastUpdated?: string;
  body?: InternationalizedArrayBodyPortableText;
  seo?: Seo;
};

export type InternationalizedArrayBodyPortableText = Array<
  {
    _key: string;
  } & InternationalizedArrayBodyPortableTextValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type HostAtRorumPage = {
  _id: string;
  _type: "hostAtRorumPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: ServiceHero;
  sessionLabel?: InternationalizedArrayString;
  sessionTitle?: InternationalizedArrayString;
  sessionImage?: ImageWithAlt;
  includedItems?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  optionalLabel?: InternationalizedArrayString;
  optionalItems?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  packagesLabel?: InternationalizedArrayString;
  packagesTitle?: InternationalizedArrayString;
  packagesIntro?: InternationalizedArrayText;
  packages?: Array<
    {
      _key: string;
    } & PackageTier
  >;
  cancellationTitle?: InternationalizedArrayString;
  cancellationItems?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  stepsTitle?: InternationalizedArrayString;
  steps?: Array<
    {
      _key: string;
    } & TitledText
  >;
  inquiryIntro?: InternationalizedArrayText;
  seo?: Seo;
};

export type ServiceHero = {
  _type: "serviceHero";
  label?: InternationalizedArrayString;
  title?: InternationalizedArrayString;
  text?: InternationalizedArrayText;
  primaryCta?: CtaLink;
  secondaryCta?: CtaLink;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroText?: InternationalizedArrayText;
  heroTrustItems?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  heroImage?: ImageWithAlt;
  heroVideoUrl?: string;
  heroPrimaryCta?: CtaLink;
  heroSecondaryCta?: CtaLink;
  quickPaths?: Array<{
    title?: InternationalizedArrayString;
    text?: InternationalizedArrayText;
    href?: string;
    image?: ImageWithAlt;
    _type: "quickPath";
    _key: string;
  }>;
  eventsLabel?: InternationalizedArrayString;
  eventsTitle?: InternationalizedArrayString;
  attendEventsFeature?: EditorialFeature;
  hostAtRorumFeature?: EditorialFeature;
  closingSection?: NextStepSection;
  seo?: Seo;
};

export type NextStepSection = {
  _type: "nextStepSection";
  eyebrow?: InternationalizedArrayString;
  title?: InternationalizedArrayString;
  text?: InternationalizedArrayText;
  cta?: CtaLink;
  faqQuestion?: InternationalizedArrayString;
  faqLabel?: InternationalizedArrayString;
  links?: Array<
    {
      _key: string;
    } & NavChild
  >;
};

export type EditorialFeature = {
  _type: "editorialFeature";
  eyebrow?: InternationalizedArrayString;
  title?: InternationalizedArrayString;
  intro?: InternationalizedArrayText;
  description?: InternationalizedArrayText;
  features?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  cta?: CtaLink;
  image?: ImageWithAlt;
  reversed?: boolean;
};

export type FormMessages = {
  _id: string;
  _type: "formMessages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  requiredFieldTemplate?: InternationalizedArrayString;
  invalidEmailMessage?: InternationalizedArrayString;
  privacyConsentRequiredMessage?: InternationalizedArrayString;
  privacyConsentLabel?: InternationalizedArrayText;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  columns?: Array<{
    title?: InternationalizedArrayString;
    links?: Array<
      {
        _key: string;
      } & NavChild
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & NavChild
  >;
  copyrightText?: InternationalizedArrayString;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroText?: InternationalizedArrayText;
  seo?: Seo;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  closingSection?: NextStepSection;
  seo?: Seo;
};

export type EventDecorationPage = {
  _id: string;
  _type: "eventDecorationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: ServiceHero;
  stylingLabel?: InternationalizedArrayString;
  stylingTitle?: InternationalizedArrayString;
  stylingIntro?: Array<
    {
      _key: string;
    } & InternationalizedArrayText
  >;
  formats?: Array<
    {
      _key: string;
    } & IconCard
  >;
  stylingImage?: ImageWithAlt;
  suitableForLabel?: InternationalizedArrayString;
  suitableFor?: Array<
    {
      _key: string;
    } & IconCard
  >;
  tailoredNote?: TitledText;
  stepsTitle?: InternationalizedArrayString;
  steps?: Array<
    {
      _key: string;
    } & TitledText
  >;
  inquiryIntro?: InternationalizedArrayText;
  seo?: Seo;
};

export type TitledText = {
  _type: "titledText";
  title?: InternationalizedArrayString;
  text?: InternationalizedArrayText;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  introTitle?: InternationalizedArrayString;
  introText?: InternationalizedArrayText;
  followUsTitle?: InternationalizedArrayString;
  formTitle?: InternationalizedArrayString;
  successMessage?: InternationalizedArrayText;
  seo?: Seo;
};

export type ContactInfo = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  phoneHref?: string;
  address?: string;
  shortAddress?: string;
  mapHref?: string;
  mapQueryAddress?: string;
};

export type CommunityMembershipPage = {
  _id: string;
  _type: "communityMembershipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroIntro?: Array<
    {
      _key: string;
    } & InternationalizedArrayText
  >;
  logo?: ImageWithAlt;
  supportCta?: CtaLink;
  externalSiteCta?: CtaLink;
  priceStripText?: InternationalizedArrayString;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  introColumns?: Array<
    {
      _key: string;
    } & TitledText
  >;
  benefitsTitle?: InternationalizedArrayString;
  benefits?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  audiencesTitle?: InternationalizedArrayString;
  audiences?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  applicationTitle?: InternationalizedArrayString;
  applicationSteps?: Array<
    {
      _key: string;
    } & TitledText
  >;
  applicationCta?: CtaLink;
  seo?: Seo;
};

export type CateringPage = {
  _id: string;
  _type: "cateringPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: ServiceHero;
  menuFormatsTitle?: InternationalizedArrayString;
  menuFormats?: Array<{
    title?: InternationalizedArrayString;
    description?: InternationalizedArrayText;
    image?: ImageWithAlt;
    _type: "menuFormatCard";
    _key: string;
  }>;
  formats?: Array<
    {
      _key: string;
    } & IconCard
  >;
  suitableForLabel?: InternationalizedArrayString;
  suitableFor?: Array<
    {
      _key: string;
    } & IconCard
  >;
  philosophyTitle?: InternationalizedArrayString;
  philosophyText?: InternationalizedArrayText;
  philosophyImage?: ImageWithAlt;
  tailoredNote?: TitledText;
  stepsTitle?: InternationalizedArrayString;
  steps?: Array<
    {
      _key: string;
    } & TitledText
  >;
  inquiryIntro?: InternationalizedArrayText;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroLead?: InternationalizedArrayText;
  statementTitle?: InternationalizedArrayString;
  statementText?: InternationalizedArrayText;
  values?: Array<
    {
      _key: string;
    } & TitledText
  >;
  pillarsLabel?: InternationalizedArrayString;
  pillars?: Array<
    {
      _key: string;
    } & TitledText
  >;
  locationTitle?: InternationalizedArrayString;
  locationText?: InternationalizedArrayText;
  locationImage?: ImageWithAlt;
  seo?: Seo;
};

export type GalleryCollection = {
  _id: string;
  _type: "galleryCollection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: Slug;
  title?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FaqGroup = {
  _id: string;
  _type: "faqGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  order?: number;
  items?: Array<{
    question?: InternationalizedArrayString;
    answer?: InternationalizedArrayText;
    _type: "faqItem";
    _key: string;
  }>;
};

export type EventCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventCategory";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  image?: ImageWithAlt;
  category?: EventCategoryReference;
  date?: string;
  time?: string;
  price?: string;
  language?: "English" | "Danish" | "Ukrainian";
  host?: string;
  isSoldOut?: boolean;
  shortDescription?: InternationalizedArrayText;
  longDescription?: InternationalizedArrayText;
  included?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  whatToExpect?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  practicalDetails?: Array<
    {
      _key: string;
    } & PracticalDetail
  >;
  ticketProvider?: string;
  ticketUrl?: string;
  calendarUrl?: string;
  waitlistUrl?: string;
  ticketsLeft?: number;
  relatedEvents?: Array<
    {
      _key: string;
    } & EventReference
  >;
  seo?: Seo;
};

export type EventCategory = {
  _id: string;
  _type: "eventCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
};

export type CateringMenuCategory = {
  _id: string;
  _type: "cateringMenuCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  navLabel?: InternationalizedArrayString;
  slug?: Slug;
  description?: InternationalizedArrayText;
  order?: number;
  featuredItems?: Array<
    {
      _key: string;
    } & CateringMenuItem
  >;
};

export type SocialLink = {
  _type: "socialLink";
  icon?: "instagram" | "facebook" | "linkedin" | "whatsapp";
  href?: string;
  label?: InternationalizedArrayString;
  brandColor?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PracticalDetail = {
  _type: "practicalDetail";
  label?: InternationalizedArrayString;
  value?: InternationalizedArrayString;
};

export type PackageTier = {
  _type: "packageTier";
  title?: InternationalizedArrayString;
  price?: InternationalizedArrayString;
  items?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
};

export type NavItem = {
  _type: "navItem";
  label?: InternationalizedArrayString;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavChild
  >;
};

export type NavChild = {
  _type: "navChild";
  href?: string;
  label?: InternationalizedArrayString;
};

export type IconCard = {
  _type: "iconCard";
  icon?:
    | "UtensilsCrossed"
    | "Flower"
    | "Balloon"
    | "Flame"
    | "BadgeCheck"
    | "ChefHat"
    | "HandPlatter"
    | "ClipboardList"
    | "CookingPot"
    | "ConciergeBell"
    | "CalendarCheck"
    | "Gem"
    | "PartyPopper"
    | "Lightbulb"
    | "Sparkles"
    | "Flower2"
    | "CircleEllipsis"
    | "Presentation"
    | "Handshake"
    | "BriefcaseBusiness"
    | "Cake"
    | "Landmark"
    | "Building2"
    | "Users";
  title?: InternationalizedArrayString;
  text?: InternationalizedArrayText;
};

export type CateringMenuItem = {
  _type: "cateringMenuItem";
  name?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  image?: ImageWithAlt;
};

export type BodyPortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type InternationalizedArrayBodyPortableTextValue = {
  _type: "internationalizedArrayBodyPortableTextValue";
  value?: BodyPortableText;
  language?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | WorkWithUsPage
  | SanityImageAssetReference
  | Seo
  | ImageWithAlt
  | InternationalizedArrayString
  | VolunteerPage
  | CtaLink
  | SocialLinks
  | SiteSettings
  | Navigation
  | LegalPage
  | InternationalizedArrayBodyPortableText
  | InternationalizedArrayText
  | HostAtRorumPage
  | ServiceHero
  | HomePage
  | NextStepSection
  | EditorialFeature
  | FormMessages
  | Footer
  | FaqPage
  | EventsPage
  | EventDecorationPage
  | TitledText
  | ContactPage
  | ContactInfo
  | CommunityMembershipPage
  | CateringPage
  | AboutPage
  | GalleryCollection
  | Slug
  | FaqGroup
  | EventCategoryReference
  | EventReference
  | Event
  | EventCategory
  | CateringMenuCategory
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | PracticalDetail
  | PackageTier
  | NavItem
  | NavChild
  | IconCard
  | CateringMenuItem
  | BodyPortableText
  | InternationalizedArrayBodyPortableTextValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/events.ts
// Variable: eventsPageQuery
// Query: *[_type == "eventsPage"][0]
export type EventsPageQueryResult = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  closingSection?: NextStepSection;
  seo?: Seo;
} | null;

// Source: sanity/queries/events.ts
// Variable: allEventsQuery
// Query: *[_type == "event"] | order(date asc){ ..., "categoryTitle": category->title }
export type AllEventsQueryResult = Array<{
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  image?: ImageWithAlt;
  category?: EventCategoryReference;
  date?: string;
  time?: string;
  price?: string;
  language?: "Danish" | "English" | "Ukrainian";
  host?: string;
  isSoldOut?: boolean;
  shortDescription?: InternationalizedArrayText;
  longDescription?: InternationalizedArrayText;
  included?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  whatToExpect?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  practicalDetails?: Array<
    {
      _key: string;
    } & PracticalDetail
  >;
  ticketProvider?: string;
  ticketUrl?: string;
  calendarUrl?: string;
  waitlistUrl?: string;
  ticketsLeft?: number;
  relatedEvents?: Array<
    {
      _key: string;
    } & EventReference
  >;
  seo?: Seo;
  categoryTitle: InternationalizedArrayString | null;
}>;

// Source: sanity/queries/events.ts
// Variable: eventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0]{    ...,    "categoryTitle": category->title,    relatedEvents[]->{ _id, title, slug, image, date }  }
export type EventBySlugQueryResult = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  image?: ImageWithAlt;
  category?: EventCategoryReference;
  date?: string;
  time?: string;
  price?: string;
  language?: "Danish" | "English" | "Ukrainian";
  host?: string;
  isSoldOut?: boolean;
  shortDescription?: InternationalizedArrayText;
  longDescription?: InternationalizedArrayText;
  included?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  whatToExpect?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  practicalDetails?: Array<
    {
      _key: string;
    } & PracticalDetail
  >;
  ticketProvider?: string;
  ticketUrl?: string;
  calendarUrl?: string;
  waitlistUrl?: string;
  ticketsLeft?: number;
  relatedEvents: Array<{
    _id: string;
    title: InternationalizedArrayString | null;
    slug: Slug | null;
    image: ImageWithAlt | null;
    date: string | null;
  }> | null;
  seo?: Seo;
  categoryTitle: InternationalizedArrayString | null;
} | null;

// Source: sanity/queries/events.ts
// Variable: allEventSlugsQuery
// Query: *[_type == "event"].slug.current
export type AllEventSlugsQueryResult = Array<string | null>;

// Source: sanity/queries/faq.ts
// Variable: faqPageQuery
// Query: *[_type == "faqPage"][0]
export type FaqPageQueryResult = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: InternationalizedArrayString;
  heroTitle?: InternationalizedArrayString;
  heroText?: InternationalizedArrayText;
  seo?: Seo;
} | null;

// Source: sanity/queries/faq.ts
// Variable: faqGroupsQuery
// Query: *[_type == "faqGroup"] | order(order asc){ _id, title, order, items }
export type FaqGroupsQueryResult = Array<{
  _id: string;
  title: InternationalizedArrayString | null;
  order: number | null;
  items: Array<{
    question?: InternationalizedArrayString;
    answer?: InternationalizedArrayText;
    _type: "faqItem";
    _key: string;
  }> | null;
}>;

// Source: sanity/queries/globals.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]
export type SiteSettingsQueryResult = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  cvr?: string;
  website?: string;
  siteUrl?: string;
  defaultSeo?: Seo;
  announcementEnabled?: boolean;
  announcementText?: InternationalizedArrayString;
  announcementLink?: CtaLink;
} | null;

// Source: sanity/queries/globals.ts
// Variable: contactInfoQuery
// Query: *[_type == "contactInfo"][0]
export type ContactInfoQueryResult = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  phoneHref?: string;
  address?: string;
  shortAddress?: string;
  mapHref?: string;
  mapQueryAddress?: string;
} | null;

// Source: sanity/queries/globals.ts
// Variable: socialLinksQuery
// Query: *[_type == "socialLinks"][0]
export type SocialLinksQueryResult = {
  _id: string;
  _type: "socialLinks";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & SocialLink
  >;
} | null;

// Source: sanity/queries/globals.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]
export type NavigationQueryResult = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & NavItem
  >;
  languageSwitcherLabel?: InternationalizedArrayString;
} | null;

// Source: sanity/queries/globals.ts
// Variable: footerQuery
// Query: *[_type == "footer"][0]
export type FooterQueryResult = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  columns?: Array<{
    title?: InternationalizedArrayString;
    links?: Array<
      {
        _key: string;
      } & NavChild
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & NavChild
  >;
  copyrightText?: InternationalizedArrayString;
} | null;

// Source: sanity/queries/globals.ts
// Variable: formMessagesQuery
// Query: *[_type == "formMessages"][0]
export type FormMessagesQueryResult = {
  _id: string;
  _type: "formMessages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  requiredFieldTemplate?: InternationalizedArrayString;
  invalidEmailMessage?: InternationalizedArrayString;
  privacyConsentRequiredMessage?: InternationalizedArrayString;
  privacyConsentLabel?: InternationalizedArrayText;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "eventsPage"][0]': EventsPageQueryResult;
    '*[_type == "event"] | order(date asc){ ..., "categoryTitle": category->title }': AllEventsQueryResult;
    '*[_type == "event" && slug.current == $slug][0]{\n    ...,\n    "categoryTitle": category->title,\n    relatedEvents[]->{ _id, title, slug, image, date }\n  }': EventBySlugQueryResult;
    '*[_type == "event"].slug.current': AllEventSlugsQueryResult;
    '*[_type == "faqPage"][0]': FaqPageQueryResult;
    '*[_type == "faqGroup"] | order(order asc){ _id, title, order, items }': FaqGroupsQueryResult;
    '*[_type == "siteSettings"][0]': SiteSettingsQueryResult;
    '*[_type == "contactInfo"][0]': ContactInfoQueryResult;
    '*[_type == "socialLinks"][0]': SocialLinksQueryResult;
    '*[_type == "navigation"][0]': NavigationQueryResult;
    '*[_type == "footer"][0]': FooterQueryResult;
    '*[_type == "formMessages"][0]': FormMessagesQueryResult;
  }
}
