// Static fallback data for the 3 `HorizontalGallery` instances (catering,
// event decoration, host-at-rorum). Used both as the frontend's fallback
// when Sanity is unreachable/empty, and as the source `scripts/import-
// gallery-images.ts` uploads from to seed each page's `galleryCollection`
// document — same "one array of truth, two consumers" pattern as
// `lib/data.ts`/`lib/cateringMenu.ts`.

export interface GalleryImage {
  src: string;
  alt: string;
}

export const cateringGalleryImages: GalleryImage[] = [
  { src: "/images/catering/catering-long-buffet.png", alt: "Long buffet table set up for a RORUM catering event" },
  { src: "/images/catering/catering-gallery-new-20.png", alt: "Spread of dishes from a RORUM catering event" },
  { src: "/images/catering/catering-membership-table.png", alt: "Catering table set up for a WECODA membership gathering" },
  { src: "/images/catering/catering-gallery-new-31.png", alt: "Plated dishes served at a RORUM catering event" },
  { src: "/images/catering/catering-gallery-added-03.png", alt: "Catering table styled for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-01.png", alt: "Dishes prepared for a RORUM catering event" },
  { src: "/images/catering/catering-buffet-table.png", alt: "Buffet table with a spread of catering dishes" },
  { src: "/images/catering/catering-gallery-new-23.png", alt: "Catering dishes arranged for a RORUM event" },
  { src: "/images/catering/catering-gallery-added-17.png", alt: "Catering spread from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-13.png", alt: "Plates of food from a RORUM catering event" },
  { src: "/images/catering/catering-welcome-drinks.png", alt: "Welcome drinks arranged for a RORUM catering event" },
  { src: "/images/catering/catering-gallery-new-07.png", alt: "Catering dishes served at a RORUM event" },
  { src: "/images/catering/catering-gallery-added-06.png", alt: "Table of catering dishes at a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-29.png", alt: "Catering plates styled for a RORUM event" },
  { src: "/images/catering/catering-ukrainian-spread.png", alt: "Spread of traditional Ukrainian dishes" },
  { src: "/images/catering/catering-gallery-new-02.png", alt: "Catering dishes from a RORUM event" },
  { src: "/images/catering/catering-gallery-added-01.png", alt: "Catering table from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-14.png", alt: "Dishes served at a RORUM catering event" },
  { src: "/images/catering/catering-dumplings.png", alt: "Traditional Ukrainian dumplings (varenyky) served on a plate" },
  { src: "/images/catering/catering-gallery-new-21.png", alt: "Catering dishes arranged on a table" },
  { src: "/images/catering/catering-gallery-added-16.png", alt: "Catering spread from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-32.png", alt: "Plated dishes from a RORUM catering event" },
  { src: "/images/catering/catering-modern-plates.png", alt: "Modern-style plated dishes for a RORUM catering event" },
  { src: "/images/catering/catering-gallery-new-04.png", alt: "Catering dishes served at a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-08.png", alt: "Table of catering dishes at a RORUM event" },
  { src: "/images/catering/catering-gallery-new-24.png", alt: "Catering plates from a RORUM event" },
  { src: "/images/catering/catering-dessert-flowers.png", alt: "Desserts styled with fresh flowers" },
  { src: "/images/catering/catering-gallery-new-10.png", alt: "Catering dishes arranged for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-13.png", alt: "Catering spread at a RORUM event" },
  { src: "/images/catering/catering-gallery-new-27.png", alt: "Plated catering dishes from a RORUM event" },
  { src: "/images/catering/catering-board.png", alt: "Appetizer board with bread, pickles and savory accompaniments" },
  { src: "/images/catering/catering-gallery-new-03.png", alt: "Catering dishes served at a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-04.png", alt: "Catering table from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-15.png", alt: "Catering dishes from a RORUM event" },
  { src: "/images/catering/catering-charcuterie.png", alt: "Charcuterie board with cheese, meats and accompaniments" },
  { src: "/images/catering/catering-gallery-new-25.png", alt: "Catering plates arranged for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-18.png", alt: "Catering spread from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-08.png", alt: "Dishes served at a RORUM catering event" },
  { src: "/images/catering/catering-borsch.png", alt: "Traditional Ukrainian borscht served with herbs" },
  { src: "/images/catering/catering-gallery-new-33.png", alt: "Catering dishes from a RORUM event" },
  { src: "/images/catering/catering-gallery-added-12.png", alt: "Catering table styled for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-11.png", alt: "Plated dishes from a RORUM catering event" },
  { src: "/images/catering/catering-dessert-table.png", alt: "Dessert table styled for a RORUM event" },
  { src: "/images/catering/catering-gallery-new-28.png", alt: "Catering dishes arranged for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-15.png", alt: "Catering spread from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-05.png", alt: "Dishes served at a RORUM catering event" },
  { src: "/images/catering/catering-cake.png", alt: "Layered cake served at a RORUM catering event" },
  { src: "/images/catering/catering-gallery-new-16.png", alt: "Catering dishes from a RORUM event" },
  { src: "/images/catering/catering-gallery-added-02.png", alt: "Catering table from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-30.png", alt: "Plated catering dishes from a RORUM event" },
  { src: "/images/catering/catering-gallery-added-05.png", alt: "Catering spread at a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-09.png", alt: "Catering dishes served at a RORUM event" },
  { src: "/images/catering/catering-gallery-added-07.png", alt: "Catering table styled for a RORUM event" },
  { src: "/images/catering/catering-gallery-new-22.png", alt: "Catering dishes from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-added-09.png", alt: "Catering spread from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-34.png", alt: "Plated dishes from a RORUM catering event" },
  { src: "/images/catering/catering-gallery-added-10.png", alt: "Catering table from a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-12.png", alt: "Catering dishes served at a RORUM event" },
  { src: "/images/catering/catering-gallery-added-11.png", alt: "Catering spread styled for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-26.png", alt: "Catering plates from a RORUM event" },
  { src: "/images/catering/catering-gallery-added-14.png", alt: "Catering table from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-06.png", alt: "Catering dishes arranged for a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-17.png", alt: "Catering dishes from a RORUM event" },
  { src: "/images/catering/catering-gallery-new-18.png", alt: "Plated dishes from a RORUM catering event" },
  { src: "/images/catering/catering-gallery-new-19.png", alt: "Catering dishes served at a RORUM gathering" },
  { src: "/images/catering/catering-gallery-new-35.png", alt: "Catering spread from a RORUM event" },
];

export const eventDecorationGalleryImages: GalleryImage[] = [
  { src: "/images/decoration/decoration-balloon-wall.png", alt: "Balloon wall decoration for a RORUM event" },
  { src: "/images/decoration/decoration-garden-pergola-dinner.png", alt: "Dinner table styled under a garden pergola" },
  { src: "/images/decoration/decoration-long-table.png", alt: "Long table styled with florals and place settings" },
  { src: "/images/decoration/decoration-modern-dining-natural-light.png", alt: "Modern dining table styled in natural daylight" },
  { src: "/images/decoration/decoration-balloon-closeup.png", alt: "Close-up of balloon decor accents" },
  { src: "/images/decoration/decoration-candlelight-dinner-table.png", alt: "Candlelit dinner table styled for an evening event" },
  { src: "/images/decoration/decoration-cake-table.png", alt: "Cake table styled with decorative accents" },
  { src: "/images/decoration/decoration-garden-reception-dusk.png", alt: "Garden reception styled at dusk" },
  { src: "/images/decoration/decoration-floral-table.png", alt: "Decorated table with flowers and place settings" },
  { src: "/images/decoration/decoration-elegant-banquet-daylight.png", alt: "Elegant banquet table styled in daylight" },
  { src: "/images/decoration/decoration-place-setting.png", alt: "Close-up of a styled table place setting" },
  { src: "/images/decoration/decoration-modern-lounge-floral-accents.png", alt: "Modern lounge area styled with floral accents" },
  { src: "/images/decoration/decoration-contrast-floral-table.png", alt: "Table styling with contrasting floral accents" },
  { src: "/images/decoration/decoration-entrance-arch.png", alt: "Decorated entrance arch for an event" },
];

export const hostAtRorumGalleryImages: GalleryImage[] = [
  { src: "/images/private-meetings/private-meeting-room-7.png", alt: "RORUM private meeting room set up for a session" },
  { src: "/images/private-meetings/private-meeting-people-1.png", alt: "People gathered in a RORUM private meeting session" },
  { src: "/images/private-meetings/private-meeting-room-3.png", alt: "RORUM private meeting room ready for guests" },
  { src: "/images/private-meetings/private-meeting-room-10.png", alt: "RORUM private meeting room with tables and chairs arranged" },
  { src: "/images/private-meetings/private-meeting-people-3.png", alt: "Small group meeting in the RORUM private meeting room" },
  { src: "/images/private-meetings/private-meeting-room-1.png", alt: "RORUM private meeting room set up for a workshop" },
  { src: "/images/private-meetings/private-meeting-room-8.png", alt: "RORUM private meeting room with a calm, organized setup" },
  { src: "/images/private-meetings/private-meeting-room-5.png", alt: "RORUM private meeting room prepared for hosting" },
  { src: "/images/private-meetings/private-meeting-people-2.png", alt: "Guests gathered for a private meeting at RORUM" },
  { src: "/images/private-meetings/private-meeting-room-11.png", alt: "RORUM private meeting room with flexible seating" },
  { src: "/images/private-meetings/private-meeting-room-2.png", alt: "RORUM private meeting room set up for a session" },
  { src: "/images/private-meetings/private-meeting-room-6.png", alt: "RORUM private meeting room with natural light" },
  { src: "/images/private-meetings/private-meeting-room-9.png", alt: "RORUM private meeting room ready for a gathering" },
  { src: "/images/private-meetings/private-meeting-room-4.png", alt: "RORUM private meeting room set up for hosting" },
];
