import { ALL_FIELDS_GROUP, defineArrayMember, defineField, defineType } from "sanity";

// This page has real "normal sections" (hero, menu formats, what-we-offer)
// plus one genuine pop-up UI element (the Catering Menu Examples overlay).
// Rather than one tab per normal section, every normal-section field is
// grouped under a single "content" tab (rendered as one continuous,
// top-to-bottom page — `fieldsets` group it visually without adding tabs),
// and only the pop-up gets its own separate tab. The built-in "All fields"
// tab is explicitly hidden so exactly 2 tabs remain: Page content and the
// Menu examples pop-up.
export default defineType({
  name: "cateringPage",
  title: "Catering page",
  type: "document",
  description: "The Catering page. / Сторінка «Кейтеринг».",
  groups: [
    { ...ALL_FIELDS_GROUP, hidden: true },
    { name: "content", title: "Page content", default: true },
    { name: "menuOverlay", title: "Menu examples pop-up" },
  ],
  fieldsets: [
    { name: "heroSection", title: "Hero", options: { collapsible: true, collapsed: false } },
    { name: "menuFormatsSection", title: "Menu formats", options: { collapsible: true, collapsed: false } },
    { name: "offerSection", title: "What we offer", options: { collapsible: true, collapsed: false } },
    { name: "inquirySection", title: "Inquiry section", options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "serviceHero", group: "content", fieldset: "heroSection" }),
    defineField({
      name: "menuFormatsTitle",
      title: "Menu formats section title",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "menuFormatsSection",
      description: "Heading above the 3 menu format cards. / Заголовок над 3 картками форматів меню.",
    }),
    defineField({
      name: "menuFormats",
      title: "Menu format cards",
      type: "array",
      group: "content",
      fieldset: "menuFormatsSection",
      description: "The 3 menu format cards (private dinner / reception / business meeting). / 3 картки форматів меню (приватна вечеря / фуршет / бізнес-зустріч).",
      of: [
        defineArrayMember({
          type: "object",
          name: "menuFormatCard",
          fields: [
            defineField({ name: "title", title: "Title", type: "internationalizedArrayString", description: "Card heading. / Заголовок картки." }),
            defineField({ name: "description", title: "Description", type: "internationalizedArrayText", description: "Card text. / Текст картки." }),
            defineField({ name: "image", title: "Image", type: "image" }),
          ],
        }),
      ],
    }),
    defineField({
      name: "formats",
      title: "\"What we offer\" cards",
      type: "array",
      group: "content",
      fieldset: "offerSection",
      of: [defineArrayMember({ type: "iconCard" })],
      description: "The icon cards describing what's offered (cuisine, buffet, custom menu, etc). / Картки з іконками про те, що пропонується (кухня, фуршет, індивідуальне меню тощо).",
    }),
    defineField({
      name: "suitableForLabel",
      title: '"Suitable for" label',
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "offerSection",
      description: 'E.g. "Suitable for:". / Напр. «Підходить для:».',
    }),
    defineField({
      name: "suitableFor",
      title: "\"Suitable for\" chips",
      type: "array",
      group: "content",
      fieldset: "offerSection",
      of: [defineArrayMember({ type: "iconCard" })],
      description: "Small chips listing occasions this service suits. / Невеликі мітки з переліком подій, для яких підходить ця послуга.",
    }),
    defineField({
      name: "philosophyTitle",
      title: "Philosophy title",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "offerSection",
      description: 'E.g. "What we offer". / Напр. «Що ми пропонуємо».',
    }),
    defineField({
      name: "philosophyText",
      title: "Philosophy text",
      type: "internationalizedArrayText",
      group: "content",
      fieldset: "offerSection",
      description: "The main paragraph describing the catering approach. / Основний абзац про підхід до кейтерингу.",
    }),
    defineField({
      name: "philosophyImage",
      title: "Philosophy image",
      type: "imageWithAlt",
      group: "content",
      fieldset: "offerSection",
      description: "Image shown next to the philosophy text. / Зображення поруч із текстом про підхід.",
    }),
    defineField({
      name: "tailoredNote",
      title: "\"Tailored upon request\" note",
      type: "titledText",
      group: "content",
      fieldset: "offerSection",
      description: "Small note that every menu can be customised. / Невелика примітка про те, що кожне меню можна адаптувати.",
    }),
    defineField({
      name: "menuOverlay",
      title: "\"View Catering Menu Examples\" popup",
      type: "object",
      group: "menuOverlay",
      description:
        "The chrome text around the category list opened by \"View Catering Menu Examples\" — the categories/dishes themselves are cateringMenuCategory documents. / Текст навколо списку категорій, що відкривається кнопкою «Переглянути приклади меню кейтерингу» — самі категорії/страви є окремими документами cateringMenuCategory.",
      fields: [
        defineField({
          name: "triggerLabel",
          title: "\"View Catering Menu Examples\" button (on the catering page itself)",
          type: "internationalizedArrayString",
          description: "Button text that opens the popup. / Текст кнопки, що відкриває спливне вікно.",
        }),
        defineField({
          name: "title",
          title: "Title",
          type: "internationalizedArrayString",
          description: 'E.g. "Catering menu". / Напр. «Меню кейтерингу».',
        }),
        defineField({
          name: "intro",
          title: "Intro paragraphs",
          type: "array",
          of: [defineArrayMember({ type: "bulletParagraph" })],
          description: "Intro paragraphs at the top of the popup. / Вступні абзаци у верхній частині спливного вікна.",
        }),
        defineField({
          name: "requestCta",
          title: "\"Request custom menu\" button",
          type: "internationalizedArrayString",
          description: "Button text. / Текст кнопки.",
        }),
        defineField({
          name: "featuredDishesLabel",
          title: "\"Featured Dishes\" heading",
          type: "internationalizedArrayString",
          description: "Heading above each category's featured dishes. / Заголовок над обраними стравами кожної категорії.",
        }),
        defineField({
          name: "disclaimerNote",
          title: "\"Examples only\" disclaimer note",
          type: "internationalizedArrayText",
          description: "Note clarifying the dishes shown are examples. / Примітка про те, що показані страви є прикладами.",
        }),
        defineField({
          name: "customMenuTitle",
          title: "\"Create your custom menu\" title",
          type: "internationalizedArrayString",
          description: "Heading of the closing section. / Заголовок завершального блоку.",
        }),
        defineField({
          name: "customMenuText",
          title: "\"Create your custom menu\" text",
          type: "internationalizedArrayText",
          description: "Text of the closing section. / Текст завершального блоку.",
        }),
        defineField({
          name: "backToCateringCta",
          title: "\"Back to Catering\" button",
          type: "internationalizedArrayString",
          description: "Button that closes the popup. / Кнопка, що закриває спливне вікно.",
        }),
      ],
    }),
    defineField({
      name: "stepsTitle",
      title: "3-step setup title",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "inquirySection",
      description: 'E.g. "3-step setup". / Напр. «3 кроки для замовлення».',
    }),
    defineField({
      name: "steps",
      title: "3-step setup",
      type: "array",
      group: "content",
      fieldset: "inquirySection",
      of: [defineArrayMember({ type: "titledText" })],
      validation: (rule) => rule.max(3),
      description: "The 3 numbered steps explaining how to book. / 3 пронумеровані кроки, що пояснюють, як замовити.",
    }),
    defineField({
      name: "inquiryIntro",
      title: "Inquiry form intro text",
      type: "internationalizedArrayText",
      group: "content",
      fieldset: "inquirySection",
      description: "Short text above the inquiry form. / Короткий текст над формою запиту.",
    }),
    defineField({
      name: "inquiryTitle",
      title: "Inquiry form title",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "inquirySection",
      description: 'E.g. "Request catering". / Напр. «Замовити кейтеринг».',
    }),
    defineField({
      name: "inquirySubmitLabel",
      title: "Inquiry form submit button",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "inquirySection",
      description: 'E.g. "Request Catering". / Напр. «Замовити кейтеринг».',
    }),
    defineField({
      name: "messagePlaceholder",
      title: "\"Message\" field placeholder",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "inquirySection",
      description: "Placeholder text shown inside the empty message field. / Текст-підказка в порожньому полі повідомлення.",
    }),
    defineField({
      name: "successMessage",
      title: "Success message",
      type: "internationalizedArrayText",
      group: "content",
      fieldset: "inquirySection",
      description: "Shown after the form is submitted successfully. / Показується після успішної відправки форми.",
    }),
    defineField({
      name: "footerNote",
      title: "Footer privacy note",
      type: "internationalizedArrayString",
      group: "content",
      fieldset: "inquirySection",
      description:
        'E.g. "We\'ll only use your details to respond to your catering request." / Напр. «Ми використаємо ваші дані лише для відповіді на запит щодо кейтерингу».',
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "content" }),
  ],
  preview: {
    prepare() {
      return { title: "Catering page" };
    },
  },
});
