import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name: "communityMembershipPage",
  title: "Community membership (WECODA) page",
  type: "document",
  description: "The WECODA community membership page. / Сторінка членства у спільноті WECODA.",
  // No `groups`/tabs: all fields render on one continuous page, in the same
  // top-to-bottom order the corresponding sections appear on the site.
  // `fieldsets` are used purely for visual (collapsible) grouping — they
  // don't split the form into tabs.
  fieldsets: [
    { name: "heroSection", title: "Hero", options: { collapsible: true, collapsed: false } },
    { name: "introSection", title: "Intro & benefits", options: { collapsible: true, collapsed: false } },
    { name: "gallerySection", title: "Gallery & price", options: { collapsible: true, collapsed: false } },
    { name: "applicationSection", title: "Application steps", options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    defineField({ name: "heroLabel", title: "Hero label", type: "internationalizedArrayString", fieldset: "heroSection", description: "Small label above the hero title. / Невеликий напис над заголовком." }),
    defineField({ name: "heroTitle", title: "Hero title", type: "internationalizedArrayString", fieldset: "heroSection", description: "Main hero heading. / Основний заголовок хіро-блоку." }),
    defineField({
      name: "heroIntro",
      title: "Hero intro paragraphs",
      type: "array",
      fieldset: "heroSection",
      of: [defineArrayMember({ type: "bulletParagraph" })],
      description: "Intro paragraphs under the hero title. / Вступні абзаци під заголовком хіро-блоку.",
    }),
    defineField({ name: "logo", title: "WECODA logo", type: "imageWithAlt", fieldset: "heroSection", description: "The WECODA logo image. / Логотип WECODA." }),
    defineField({ name: "supportCta", title: "\"Support WECODA\" button", type: "ctaLink", fieldset: "heroSection" }),
    defineField({ name: "externalSiteCta", title: "\"WECODA website\" link", type: "ctaLink", fieldset: "heroSection" }),
    defineField({
      name: "donation",
      title: "Donation section",
      type: "object",
      description:
        "Bank details (Beneficiary, CVR, IBAN, etc.) are NOT localized here — they're facts, hardcoded in components/WecodaDonationSection.tsx. / Банківські реквізити (отримувач, CVR, IBAN тощо) тут НЕ перекладаються — це факти, зашиті в коді components/WecodaDonationSection.tsx.",
      fields: [
        defineField({ name: "label", title: "Section label", type: "internationalizedArrayString", description: 'E.g. "Donation". / Напр. «Пожертва».' }),
        defineField({ name: "title", title: "Section title", type: "internationalizedArrayString", description: 'E.g. "Support the WECODA Community". / Напр. «Підтримайте спільноту WECODA».' }),
        defineField({ name: "text", title: "Intro text", type: "internationalizedArrayText", description: "Paragraph explaining what the donation supports. / Абзац про те, на що йде пожертва." }),
        defineField({ name: "scanText", title: "\"Scan to donate\"", type: "internationalizedArrayString", description: 'E.g. "Scan to donate". / Напр. «Скануйте, щоб зробити пожертву».' }),
        defineField({ name: "scanSubtext", title: "\"Fast, secure and easy.\"", type: "internationalizedArrayString", description: 'E.g. "Fast, secure and easy." / Напр. «Швидко, безпечно та просто».' }),
        defineField({ name: "orText", title: "\"OR\" separator", type: "internationalizedArrayString", description: 'The word "OR" between QR code and bank transfer. / Слово «АБО» між QR-кодом і банківським переказом.' }),
        defineField({
          name: "bankTransferText",
          title: "\"Prefer bank transfer?\" line",
          type: "internationalizedArrayString",
          description: 'E.g. "Prefer bank transfer? See our bank details on the right." / Напр. «Надаєте перевагу банківському переказу? Реквізити наведено праворуч».',
        }),
        defineField({ name: "bankDetailsTitle", title: "\"Bank Details\" heading", type: "internationalizedArrayString", description: 'E.g. "Bank Details". / Напр. «Банківські реквізити».' }),
        defineField({ name: "supportText", title: "Closing support text", type: "internationalizedArrayText", description: "Closing paragraph thanking donors. / Завершальний абзац із подякою донорам." }),
      ],
    }),
    defineField({
      name: "priceStripText",
      title: "Price strip text",
      type: "internationalizedArrayString",
      fieldset: "gallerySection",
      description: 'E.g. "Annual membership price: 250 DKK". / Напр. «Річна вартість членства: 250 DKK».',
    }),
    defineField({
      name: "galleryLabel",
      title: "Gallery section label",
      type: "internationalizedArrayString",
      fieldset: "gallerySection",
      description: 'E.g. "Gallery". / Напр. «Галерея».',
    }),
    defineField({
      name: "galleryTitle",
      title: "Gallery section title",
      type: "internationalizedArrayString",
      fieldset: "gallerySection",
      description: 'E.g. "WECODA Community Meetings". / Напр. «Зустрічі спільноти WECODA».',
    }),
    defineField({
      name: "gallery",
      title: "Gallery images",
      type: "array",
      fieldset: "gallerySection",
      of: [defineArrayMember({ type: "imageWithAlt" })],
      description: "Photos shown in the community gallery grid. / Фото у сітці галереї спільноти.",
    }),
    defineField({
      name: "introSectionLabel",
      title: "Intro section label",
      type: "internationalizedArrayString",
      fieldset: "introSection",
      description: 'E.g. "WECODA community". / Напр. «Спільнота WECODA».',
    }),
    defineField({
      name: "introSectionTitle",
      title: "Intro section title",
      type: "internationalizedArrayString",
      fieldset: "introSection",
      description: 'E.g. "Connecting Women Who Inspire, Build and Lead." / Напр. «Об\'єднуємо жінок, які надихають, будують і ведуть за собою».',
    }),
    defineField({
      name: "introColumns",
      title: "Intro columns",
      type: "array",
      fieldset: "introSection",
      of: [defineArrayMember({ type: "titledText" })],
      description: "The 2 intro paragraphs shown side by side. / 2 вступні абзаци, що показуються поруч.",
    }),
    defineField({
      name: "benefitsTitle",
      title: "Benefits section title",
      type: "internationalizedArrayString",
      fieldset: "introSection",
      description: 'E.g. "What You Gain as a Member". / Напр. «Що ви отримуєте як учасниця».',
    }),
    defineField({
      name: "benefits",
      title: "Benefits",
      type: "array",
      fieldset: "introSection",
      of: [defineArrayMember({ type: "bulletText" })],
      description: "Each benefit as \"Title — Description\" in one line. / Кожна перевага у форматі «Назва — опис» одним рядком.",
    }),
    defineField({
      name: "audiencesTitle",
      title: "\"Who it's for\" title",
      type: "internationalizedArrayString",
      fieldset: "introSection",
      description: "Heading for the \"who this is for\" list (not currently shown on the site). / Заголовок для списку «кому це підходить» (наразі не показується на сайті).",
    }),
    defineField({
      name: "audiences",
      title: "Audiences",
      type: "array",
      fieldset: "introSection",
      of: [defineArrayMember({ type: "bulletText" })],
      description: "List of who the membership is aimed at (not currently shown on the site). / Список тих, кому призначене членство (наразі не показується на сайті).",
    }),
    defineField({
      name: "applicationTitle",
      title: "Application section title",
      type: "internationalizedArrayString",
      fieldset: "applicationSection",
      description: 'E.g. "Application Process". / Напр. «Процес подачі заявки».',
    }),
    defineField({
      name: "applicationSteps",
      title: "Application steps",
      type: "array",
      fieldset: "applicationSection",
      of: [defineArrayMember({ type: "titledText" })],
      description: "The numbered steps to become a member. / Пронумеровані кроки для того, щоб стати учасницею.",
    }),
    defineField({
      name: "applicationCta",
      title: "Application button",
      type: "ctaLink",
      fieldset: "applicationSection",
      description: 'E.g. "Become a Member". / Напр. «Стати учасницею».',
    }),
    defineField({ name: "seo", title: "SEO", type: "seo" }),
  ],
  preview: {
    prepare() {
      return { title: "Community membership page" };
    },
  },
});
