import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name: "eventDecorationPage",
  title: "Event decoration page",
  type: "document",
  description: "The Event Decoration page. / Сторінка «Декор подій».",
  // No `groups`/tabs: all fields render on one continuous page, in the same
  // top-to-bottom order the corresponding sections appear on the site.
  fieldsets: [
    { name: "gallerySection", title: "Gallery & \"Suitable for\"", options: { collapsible: true, collapsed: false } },
    { name: "stylingSection", title: "What we style", options: { collapsible: true, collapsed: false } },
    { name: "inquirySection", title: "Inquiry section", options: { collapsible: true, collapsed: false } },
    { name: "seoSection", title: "SEO", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "serviceHero" }),
    defineField({
      name: "gallery",
      title: "Gallery images",
      type: "array",
      fieldset: "gallerySection",
      of: [defineArrayMember({ type: "imageWithAlt" })],
      description: "The photos shown in the decoration gallery, in order. / Фото в галереї декору, у порядку показу.",
    }),
    defineField({
      name: "suitableForLabel",
      title: '"Suitable for" label',
      type: "internationalizedArrayString",
      fieldset: "gallerySection",
      description: 'E.g. "Suitable for:". / Напр. «Підходить для:».',
    }),
    defineField({
      name: "suitableFor",
      title: "\"Suitable for\" chips",
      type: "array",
      fieldset: "gallerySection",
      of: [defineArrayMember({ type: "iconCard" })],
      description: "Small chips listing occasions this service suits. / Невеликі мітки з переліком подій, для яких підходить ця послуга.",
    }),
    defineField({
      name: "suitableForAriaLabel",
      title: "\"Suitable for\" chips accessible label",
      type: "internationalizedArrayString",
      fieldset: "gallerySection",
      description: "Screen-reader label for the chip group (not visible). / Напис для програм читання з екрана для групи міток (не показується візуально).",
    }),
    defineField({
      name: "stylingLabel",
      title: '"What we style" label',
      type: "internationalizedArrayString",
      fieldset: "stylingSection",
      description: 'E.g. "Decoration". / Напр. «Декор».',
    }),
    defineField({
      name: "stylingTitle",
      title: '"What we style" title',
      type: "internationalizedArrayString",
      fieldset: "stylingSection",
      description: 'E.g. "What we style". / Напр. «Що ми оформлюємо».',
    }),
    defineField({
      name: "stylingIntro",
      title: "Intro paragraphs",
      type: "array",
      fieldset: "stylingSection",
      of: [defineArrayMember({ type: "bulletParagraph" })],
      description: "Intro paragraphs describing the styling approach. / Вступні абзаци про підхід до оформлення.",
    }),
    defineField({
      name: "formats",
      title: "Decoration format cards",
      type: "array",
      fieldset: "stylingSection",
      of: [defineArrayMember({ type: "iconCard" })],
      description: "Icon cards for table styling / florals / balloons / etc. / Картки з іконками для сервірування столу / флористики / кульок тощо.",
    }),
    defineField({
      name: "stylingImage",
      title: "\"What we style\" image",
      type: "imageWithAlt",
      fieldset: "stylingSection",
      description: "Image shown next to the styling intro. / Зображення поруч зі вступним текстом про оформлення.",
    }),
    defineField({
      name: "tailoredNote",
      title: "\"Tailored upon request\" note",
      type: "titledText",
      fieldset: "stylingSection",
      description: "Small note that every setup is customised. / Невелика примітка про те, що кожне оформлення індивідуальне.",
    }),
    defineField({
      name: "stepsTitle",
      title: "3-step setup title",
      type: "internationalizedArrayString",
      fieldset: "inquirySection",
      description: 'E.g. "3-step setup". / Напр. «3 кроки для замовлення».',
    }),
    defineField({
      name: "steps",
      title: "3-step setup",
      type: "array",
      fieldset: "inquirySection",
      of: [defineArrayMember({ type: "titledText" })],
      validation: (rule) => rule.max(3),
      description: "The 3 numbered steps explaining how to book. / 3 пронумеровані кроки, що пояснюють, як замовити.",
    }),
    defineField({
      name: "inquiryIntro",
      title: "Inquiry form intro text",
      type: "internationalizedArrayText",
      fieldset: "inquirySection",
      description: "Short text above the inquiry form. / Короткий текст над формою запиту.",
    }),
    defineField({
      name: "inquiryTitle",
      title: "Inquiry form title",
      type: "internationalizedArrayString",
      fieldset: "inquirySection",
      description: 'E.g. "Decoration request". / Напр. «Запит на декор».',
    }),
    defineField({
      name: "inquirySubmitLabel",
      title: "Inquiry form submit button",
      type: "internationalizedArrayString",
      fieldset: "inquirySection",
      description: 'E.g. "Send request". / Напр. «Надіслати запит».',
    }),
    defineField({
      name: "messagePlaceholder",
      title: "\"Message\" field placeholder",
      type: "internationalizedArrayString",
      fieldset: "inquirySection",
      description: "Placeholder text shown inside the empty message field. / Текст-підказка в порожньому полі повідомлення.",
    }),
    defineField({
      name: "successMessage",
      title: "Success message",
      type: "internationalizedArrayText",
      fieldset: "inquirySection",
      description: "Shown after the form is submitted successfully. / Показується після успішної відправки форми.",
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", fieldset: "seoSection" }),
  ],
  preview: {
    prepare() {
      return { title: "Event decoration page" };
    },
  },
});
