import type { PageContentContract } from "./types";

/**
 * Machine-readable content contract for the About page
 * (app/[locale]/(site)/about/page.tsx <- sections[] on the `page-about`
 * document, see sanity/schemaTypes/documents/page.ts).
 *
 * Updated after the approved Studio Visibility Contract implementation pass
 * (see the "Studio Visibility Contract" and its follow-up implementation
 * report artifacts). Fixed this pass, reflected below:
 *  - `statement.text` / `community.text` / `pillars.text` are now ALSO
 *    visible in Studio (narrowly scoped to page-about, see
 *    pageSection.ts's ABOUT_TEXT_FORCE_VISIBLE_SECTION_KEYS) — previously
 *    connected-in-code but invisible-in-Studio, now genuinely both.
 *  - `closingCta.actions[main].href/openInNewTab/enabled` are now wired via
 *    the shared resolveAction() helper (previously hardcoded JSX literals).
 *  - `closingCta.settings[variant]` — correction, not a fix: this field was
 *    already Studio-hidden (sectionKind "cta" never shows `settings`); the
 *    original report calling it "visible" was wrong. See Approved Fix 7.
 *  - `seo.title`/`seo.description` are now wired with the same
 *    locale-aware fallback chain Home uses. Content remains EMPTY in
 *    Sanity for both — not populated this phase. "Connected" below means
 *    the code path is correct for both the populated and empty branches,
 *    not that content exists; do not read "connected" as "content-complete"
 *    for these two entries.
 * `hero.actions` is now explicitly Studio-hidden for page-about only (was
 * previously visible-but-unused).
 */
export const aboutContract: PageContentContract = {
  pageKey: "about",
  documentId: "page-about",
  documentType: "page",
  entries: [
    // ---- hero ------------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].label`,
      fieldPurpose: "Hero eyebrow label ('About')",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "app/[locale]/(site)/about/page.tsx:getData (heroLabel)",
      component: "SectionLabel",
      frontendSelector: `[aria-label] n/a — SectionLabel above the H1, first Container in the hero section`,
      expectedBehavior: "Shows the localized label, or 'About' if unset for this locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production (en/da/uk all populated).",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].title`,
      fieldPurpose: "Hero H1 ('About RORUM')",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "app/[locale]/(site)/about/page.tsx:getData (heroTitle)",
      component: "about/page.tsx <h1>",
      frontendSelector: `page.getByRole('heading', { level: 1 })`,
      expectedBehavior: "Renders the localized title as the page's only H1.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].text`,
      fieldPurpose: "Hero lead paragraph",
      fieldType: "i18nText",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "app/[locale]/(site)/about/page.tsx:getData (heroLead)",
      component: "about/page.tsx <p> under the H1",
      frontendSelector: `page.getByText(value, { exact: true })`,
      expectedBehavior: "Renders the localized paragraph under the H1.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].items[itemKey=="intro0"]`,
      fieldPurpose: "Quick-link chip 1 under the hero (label/href/icon) — 'Host at RORUM'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(heroSection))",
      component: "about/page.tsx introLinks map -> LocaleLink",
      frontendSelector: `[aria-label="RORUM event paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts, run live and verified idempotent) — previously EN-only, falling back to the English string via pickLocalized.",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].items[itemKey=="intro1"]`,
      fieldPurpose: "Quick-link chip 2 under the hero (label/href/icon) — 'Attend Events'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(heroSection))",
      component: "about/page.tsx introLinks map -> LocaleLink",
      frontendSelector: `[aria-label="RORUM event paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — same fix as intro0.",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].media[0..2].image`,
      fieldPurpose: "3 atmosphere photos beside the hero copy",
      fieldType: "image",
      required: true,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (atmosphereImages, urlForImage)",
      component: "about/page.tsx atmosphereImages map -> <img>",
      frontendSelector: `[aria-label="RORUM atmosphere"] img`,
      expectedBehavior: "Renders 3 real Sanity CDN images in array order (first one spans 2 rows).",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "connected",
      notes: "All 3 media items populated with real Sanity assets already (no fallback/local image in use).",
    },
    {
      pageKey: "about",
      sectionKey: "hero",
      sanityPath: `sections[sectionKey=="hero"].media[0..2].alt`,
      fieldPurpose: "Alt text for the 3 atmosphere photos (meaningful images — not decorative)",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (atmosphereImages[].alt, pickLocalized)",
      component: "about/page.tsx atmosphereImages map -> <img alt>",
      frontendSelector: `[aria-label="RORUM atmosphere"] img >> attribute:alt`,
      expectedBehavior: "img[alt] equals the localized alt text for each of the 3 images.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk alt text now populated for all 3 images (scripts/backfill-about-translations.ts, verified idempotent) — previously EN-only. These ARE meaningful/informative images so alt text is required, unlike Home's decorative backgrounds.",
    },
    // ---- statement ---------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "statement",
      sanityPath: `sections[sectionKey=="statement"].title`,
      fieldPurpose: "'Services' sub-heading",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (statementTitle)",
      component: "about/page.tsx <h2> (statement block)",
      frontendSelector: `page.getByRole('heading', { level: 2, name: value })`,
      expectedBehavior: "Renders the localized sub-heading above the services paragraph.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "statement",
      sanityPath: `sections[sectionKey=="statement"].text`,
      fieldPurpose: "Services statement paragraph",
      fieldType: "i18nText",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (statementText)",
      component: "about/page.tsx <p> (statement block)",
      frontendSelector: `page.getByText(value, { exact: true })`,
      expectedBehavior: "Renders the localized paragraph, fully localized in production.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: rendered from real, populated data and now correctly visible+editable in Studio. sectionKind=\"iconGrid\" still hides \"text\" by default (pageSection.ts FIELD_VISIBILITY.iconGrid = {label,title,items}), but pageSection.ts's ABOUT_TEXT_FORCE_VISIBLE_SECTION_KEYS narrowly force-shows it for page-about's statement/community/pillars sections specifically — not added to iconGrid globally, so catering.menuFormats/workWithUs.features (also iconGrid, no text content) are unaffected.",
    },
    {
      pageKey: "about",
      sectionKey: "statement",
      sanityPath: `sections[sectionKey=="statement"].items[itemKey=="service0"]`,
      fieldPurpose: "Quick-link chip — 'Catering'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(statementSection))",
      component: "about/page.tsx serviceLinks map -> LocaleLink",
      frontendSelector: `[aria-label="RORUM service paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — previously EN-only, falling back to English text on da/uk.",
    },
    {
      pageKey: "about",
      sectionKey: "statement",
      sanityPath: `sections[sectionKey=="statement"].items[itemKey=="service1"]`,
      fieldPurpose: "Quick-link chip — 'Event Decoration'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(statementSection))",
      component: "about/page.tsx serviceLinks map -> LocaleLink",
      frontendSelector: `[aria-label="RORUM service paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — same fix as service0.",
    },
    // ---- community ---------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "community",
      sanityPath: `sections[sectionKey=="community"].title`,
      fieldPurpose: "'Community' sub-heading",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (communityTitle)",
      component: "about/page.tsx <h2> (community block)",
      frontendSelector: `page.getByRole('heading', { level: 2, name: value })`,
      expectedBehavior: "Renders the localized sub-heading, or falls back to English if untranslated.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts, verified idempotent) — previously EN-only, rendering the English word 'Community' on da/uk pages.",
    },
    {
      pageKey: "about",
      sectionKey: "community",
      sanityPath: `sections[sectionKey=="community"].text`,
      fieldPurpose: "Community paragraph",
      fieldType: "i18nText",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (communityText)",
      component: "about/page.tsx <p> (community block)",
      frontendSelector: `page.getByText(value, { exact: true })`,
      expectedBehavior: "Renders the localized paragraph, fully localized in production.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: same treatment as statement.text above — now correctly visible+editable in Studio via ABOUT_TEXT_FORCE_VISIBLE_SECTION_KEYS. Data itself is fully localized and renders correctly.",
    },
    {
      pageKey: "about",
      sectionKey: "community",
      sanityPath: `sections[sectionKey=="community"].items[itemKey=="community0"]`,
      fieldPurpose: "Quick-link chip — 'WECODA membership'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(communitySection))",
      component: "about/page.tsx communityQuickLinks map -> LocaleLink",
      frontendSelector: `[aria-label="Community paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — previously EN-only.",
    },
    {
      pageKey: "about",
      sectionKey: "community",
      sanityPath: `sections[sectionKey=="community"].items[itemKey=="community1"]`,
      fieldPurpose: "Quick-link chip — 'Work with us'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(communitySection))",
      component: "about/page.tsx communityQuickLinks map -> LocaleLink",
      frontendSelector: `[aria-label="Community paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — previously EN-only.",
    },
    {
      pageKey: "about",
      sectionKey: "community",
      sanityPath: `sections[sectionKey=="community"].items[itemKey=="community2"]`,
      fieldPurpose: "Quick-link chip — 'Volunteer with us'",
      fieldType: "keyedString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (resolveIconLinksFromSection(communitySection))",
      component: "about/page.tsx communityQuickLinks map -> LocaleLink",
      frontendSelector: `[aria-label="Community paths"] a`,
      expectedBehavior: "Renders a pill link with the localized label, resolved icon and href.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED: da/uk now populated (scripts/backfill-about-translations.ts) — previously EN-only.",
    },
    // ---- pillars -----------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "pillars",
      sanityPath: `sections[sectionKey=="pillars"].label`,
      fieldPurpose: "'Experience principles' eyebrow label",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (pillarsLabel)",
      component: "SectionLabel (pillars block)",
      frontendSelector: `page.getByText(value, { exact: true })`,
      expectedBehavior: "Renders the localized label above the location title.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "pillars",
      sanityPath: `sections[sectionKey=="pillars"].title`,
      fieldPurpose: "'Thoughtful and practical' heading",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (locationTitle)",
      component: "about/page.tsx <h2> (pillars block)",
      frontendSelector: `page.getByRole('heading', { level: 2, name: value })`,
      expectedBehavior: "Renders the localized heading.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "pillars",
      sanityPath: `sections[sectionKey=="pillars"].text`,
      fieldPurpose: "Pillars intro paragraph",
      fieldType: "i18nText",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (locationText)",
      component: "about/page.tsx <p> (pillars block)",
      frontendSelector: `page.getByText(value, { exact: true })`,
      expectedBehavior: "Renders the localized paragraph.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "pillars",
      sanityPath: `sections[sectionKey=="pillars"].items[0..3]`,
      fieldPurpose: "4 principle cards (title + text) — Calm first / Useful hospitality / Flexible but not blank / Personal without noise",
      fieldType: "repeatable",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (pillars)",
      component: "about/page.tsx pillars map",
      frontendSelector: `page.getByRole('heading', { level: 3, name: title })`,
      expectedBehavior: "Renders 4 cards in array order, each numbered 01-04, with localized title+text.",
      mutationStrategy: "reorder",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Best-translated section on the page — all 4 items fully populated in en/da/uk, no gaps.",
    },
    // ---- closingCta ----------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].label`,
      fieldPurpose: "'Not sure where to start?' eyebrow",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingEyebrow)",
      component: "CTASection eyebrow",
      frontendSelector: `.next-step-section-not-sure`,
      expectedBehavior: "Renders the localized eyebrow text.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].title`,
      fieldPurpose: "'Let's shape your idea together' heading",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingTitle)",
      component: "CTASection title",
      frontendSelector: `.next-step-section-not-sure`,
      expectedBehavior: "Renders the localized heading.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].text`,
      fieldPurpose: "Closing paragraph",
      fieldType: "i18nText",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingText)",
      component: "CTASection text",
      frontendSelector: `.next-step-section-not-sure`,
      expectedBehavior: "Renders the localized paragraph.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"].label`,
      fieldPurpose: "CTA button label — 'Let's talk'",
      fieldType: "i18nString",
      required: true,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingCta, via getAction(...).label)",
      component: "CTASection Button label",
      frontendSelector: `.next-step-section-not-sure a`,
      expectedBehavior: "Renders the localized button label.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"].href`,
      fieldPurpose: "CTA button destination",
      fieldType: "link",
      required: true,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingMainAction, via the shared resolveAction() helper)",
      component: "about/page.tsx: <CTASection href={closingMainAction?.href} .../>",
      frontendSelector: `.next-step-section-not-sure a >> attribute:href`,
      expectedBehavior: "Renders the CTA's real Sanity-configured destination.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED this pass: now routed through resolveAction(), same as every Home CTA. Verified the rendered destination is unchanged with current production data (still resolves to \"/contact\").",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"].openInNewTab`,
      fieldPurpose: "Whether the CTA opens in a new tab",
      fieldType: "boolean",
      required: false,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingMainAction, via resolveAction())",
      component: "about/page.tsx: <CTASection target={closingMainAction?.target} rel={closingMainAction?.rel} .../>",
      frontendSelector: `.next-step-section-not-sure a >> attribute:target`,
      expectedBehavior: "true opens the link in a new tab with rel=\"noopener noreferrer\"; false (default) keeps the current tab.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED this pass via resolveAction(). Verified with current production data (false): no target/rel is applied, unchanged from before.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"].enabled`,
      fieldPurpose: "Whether the CTA button renders at all",
      fieldType: "boolean",
      required: false,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingMainAction, via resolveAction())",
      component: "about/page.tsx: <CTASection href={closingMainAction?.href} .../> (CTASection renders no button when href is undefined)",
      frontendSelector: `.next-step-section-not-sure a`,
      expectedBehavior: "enabled=false resolves closingMainAction to undefined, so href/label are undefined and CTASection renders no button — same pattern Home already uses.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED this pass: now routed through resolveAction(), same as every Home CTA. Verified with current production data (enabled=true): button still renders unchanged.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].items[itemKey=="faqQuestion"].title`,
      fieldPurpose: "'Have questions?' FAQ prompt text",
      fieldType: "i18nString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingFaqQuestion, via getItem)",
      component: "FAQInlinePrompt question",
      frontendSelector: `.next-step-section-not-sure`,
      expectedBehavior: "Renders the localized FAQ prompt text.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].items[itemKey=="faqLabel"].title`,
      fieldPurpose: "'Read our FAQs' link label",
      fieldType: "i18nString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingFaqLabel, via getItem)",
      component: "FAQInlinePrompt label",
      frontendSelector: `.next-step-section-not-sure`,
      expectedBehavior: "Renders the localized FAQ link label.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].items[itemKey=~"^link"]`,
      fieldPurpose: "4 suggested-path chips (Attend Events / Host at RORUM / Catering / Event decoration)",
      fieldType: "repeatable",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (closingLinks, filters items by itemKey.startsWith('link'))",
      component: "CTASection links map",
      frontendSelector: `[aria-label="Suggested paths"] a`,
      expectedBehavior: "Renders 4 chips in array order with localized label + href.",
      mutationStrategy: "reorder",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Fully localized in production, all 4 links.",
    },
    {
      pageKey: "about",
      sectionKey: "closingCta",
      sanityPath: `sections[sectionKey=="closingCta"].settings[key=="variant"].value`,
      fieldPurpose: "Visual variant flag for the closing CTA card",
      fieldType: "rawString",
      required: false,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "n/a — not read",
      component: "about/page.tsx: <CTASection variant=\"final\" .../> (JSX literal)",
      frontendSelector: `n/a`,
      expectedBehavior: "CORRECTION (Studio Visibility Contract audit): this field is actually hidden in Studio already — sectionKind \"cta\" doesn't include \"settings\" in pageSection.ts's FIELD_VISIBILITY, same mechanism as Home's equivalent field. The original report calling this \"visible\" was wrong. The frontend still hardcodes variant=\"final\" and never reads it (Approved Fix 7: keep hidden, do not wire, decision on removal deferred).",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "technical-hidden",
      notes: "Stored value \"final\" preserved, unread by both Studio (hidden) and the frontend (hardcoded). No code/schema change made for this field this pass beyond the correction above — see Approved Fix 7 (deferred: field-removal decision after all pages audited).",
    },
    // ---- SEO -----------------------------------------------------------------
    {
      pageKey: "about",
      sectionKey: "seo",
      sanityPath: `seo.title`,
      fieldPurpose: "Browser-tab / search-result title",
      fieldType: "i18nString",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (seoTitle = pickLocalized(newPage?.seo?.title, locale) ?? fallback.seoTitle)",
      component: "app/[locale]/(site)/about/page.tsx:generateMetadata",
      frontendSelector: `page.title()`,
      expectedBehavior: "Renders the localized SEO title once populated; falls back to the hardcoded \"About\" string when empty for this locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED this pass: now wired the same way Home's seo.title is. Content is still EMPTY in Sanity for all 3 languages as of this change — classify as connected-in-code, empty-in-content; do not call this field's content complete. Not populated this phase per instruction.",
    },
    {
      pageKey: "about",
      sectionKey: "seo",
      sanityPath: `seo.description`,
      fieldPurpose: "Search-result / social-share description",
      fieldType: "i18nText",
      required: false,
      languages: ["en", "da", "uk"],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (description = pickLocalized(newPage?.seo?.description, locale) ?? fallback.description)",
      component: "app/[locale]/(site)/about/page.tsx:generateMetadata",
      frontendSelector: `page.locator('meta[name="description"]')`,
      expectedBehavior: "Renders the localized SEO description once populated; falls back to the hardcoded default when empty for this locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "FIXED this pass: now reads `newPage` (the real, editable page-about field) instead of the dead legacy `aboutPage` singleton (confirmed 0 documents). \"Connected\" means the code path is correct for both branches, not that content is populated — content is still EMPTY in Sanity for all 3 languages; not populated this phase per instruction. Distinguish \"connected in code\" from \"populated in Sanity\".",
    },
    {
      pageKey: "about",
      sectionKey: "seo",
      sanityPath: "seo.ogImage",
      fieldPurpose: "Social Sharing Image (og:image) for the About page",
      fieldType: "image",
      required: false,
      languages: [],
      querySource: "sanity/queries/page.ts:pageByKeyQuery",
      mapper: "about/page.tsx:getData (ogImageUrl = urlForImage(newPage?.seo?.ogImage)), passed to generateMetadata()'s localizedPageMetadata() call",
      component: "app/[locale]/(site)/about/page.tsx:generateMetadata",
      frontendSelector: `page.locator('meta[property="og:image"]')`,
      expectedBehavior: "When an editor uploads a Social Sharing Image, that photo's URL is used for og:image; otherwise the existing hardcoded default is used, unchanged from before.",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Wired this pass — same fix as Home's equivalent entry (own generateMetadata() call, plus a shared " +
        "lib/seo.ts bug fix for already-absolute image URLs). About's own ogImage content is currently unset.",
    },
    // ---- legacy singleton (dead data path) ------------------------------------
    {
      pageKey: "about",
      sectionKey: "(legacy)",
      sanityPath: `*[_type == "aboutPage"] (whole document type)`,
      fieldPurpose: "Original per-page singleton this page was migrated FROM (heroLabel, heroTitle, heroLead, statementTitle/Text, atmosphereImages, introLinks, serviceLinks, communityTitle/Text, communityLinks, values (already hidden), pillarsLabel, pillars, locationTitle/Text, locationImage, closingSection, seo — 17 top-level fields)",
      fieldType: "repeatable",
      required: false,
      languages: [],
      querySource: "sanity/queries/pages.ts:aboutPageQuery",
      mapper: "about/page.tsx:getData — used only as a third-priority fallback behind sections[] and before the hardcoded `fallback` object",
      component: "n/a",
      frontendSelector: `n/a`,
      expectedBehavior: "Never resolves to anything: 0 documents of type \"aboutPage\" exist (confirmed via read-only query, any id). The schema type is also not reachable from Studio's navigation (sanity/structure.ts only lists the new page-about document under \"About\").",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "obsolete-deferred",
      notes: "DONE (R8 cleanup, SANITY_MIGRATION.md §20.8): the `aboutPage` schema type, `aboutPageQuery`, the `about/page.tsx` fetch and every `?? page?.X` fallback tier have all been removed. This entry is now fully historical — the field no longer exists anywhere.",
    },
  ],
};
