import { locales } from "@/lib/i18n";
import type { PageContentContract } from "@/lib/content-contracts/types";

const ALL = locales; // ["en", "da", "uk"]
const LISTING_QUERY = 'sanity/queries/page.ts (pageByKeyQuery, pageKey="events")';
const EVENT_QUERY = "sanity/queries/events.ts (eventBySlugQuery / allEventsQuery)";
const MESSAGES_QUERY = "sanity/queries/globals.ts (eventMessagesQuery)";
const MAPPER = "lib/sanityEvents.ts (sanityEventToRorumEvent)";

/**
 * Events content contract — covers the Events listing page (`page-events`),
 * every `event` document, and the shared `eventMessages` singleton. Sourced
 * by reading sanity/schemaTypes/documents/{event,page}.ts,
 * sanity/schemaTypes/singletons/{eventMessages,eventsPage}.ts,
 * sanity/queries/{events,page,globals}.ts, lib/sanityEvents.ts,
 * lib/sanity-sections.ts, and every line of getData()/generateMetadata() in
 * app/[locale]/(site)/events/page.tsx and events/[slug]/page.tsx, cross-
 * checked against the live page-events / event / eventMessages documents
 * (raw perspective, read-only fetch — no writes).
 *
 * Legacy `eventsPage` singleton is NOT documented here as a content source —
 * see events-studio-visibility.ts's own entry explaining why it was removed
 * from the active read path (no published document exists; page-events is
 * the sole authoritative source going forward).
 */
export const eventsContract: PageContentContract = {
  pageKey: "events",
  documentId: "page-events",
  documentType: "page",
  entries: [
    // ---- listing: hero ---------------------------------------------------
    {
      pageKey: "events",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].title',
      fieldPurpose: "Events listing H1",
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx getData() title",
      component: "components/ui.tsx SectionHeader (<h1>, level=1)",
      frontendSelector: 'getByRole("heading", {level: 1})',
      expectedBehavior: "H1 text matches the edited value in the requested locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Fixed this pass: generateMetadata() previously hardcoded the <title> tag to the literal string \"Events\" " +
        "regardless of this field — now reads newPage's hero title (falling back to the same hardcoded default) " +
        "for both the rendered H1 and the <title> tag.",
    },

    // ---- listing: filters --------------------------------------------------
    {
      pageKey: "events",
      sectionKey: "filters",
      sanityPath: 'sections[sectionKey=="filters"].items[itemKey=~"dateLabel|languageLabel|priceLabel|availabilityLabel|soonestLabel|weekLabel|monthLabel|priceAscLabel|priceDescLabel|availableLabel|soldOutLabel|clearFiltersLabel"].title',
      fieldPurpose: "11 filter-bar labels (Date/Language/Price/Availability headings + their option labels + Clear filters)",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx getData() filters object, one getItem(...)?.title per itemKey",
      component: "components/EventFilters.tsx",
      frontendSelector: '[data-testid="events-filter-*"] labels (per filter control)',
      expectedBehavior: "Each label's text changes to the edited value in the requested locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Each row only ever populates `.title` — `.icon`/`.text`/`.label`/`.href`/`.value` are unused on every one " +
        "of these 13 items (confirmed live: all null). Hidden this pass via a new ITEM_ROLE_RULES entry.",
    },
    {
      pageKey: "events",
      sectionKey: "filters",
      sanityPath: 'sections[sectionKey=="filters"].items[itemKey="emptyStateTitle"/"emptyStateText"].title',
      fieldPurpose: "Empty-state heading + body text (shown when no events match the current filters)",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx getData() emptyState",
      component: "components/EventsPaginatedList.tsx",
      frontendSelector: '[data-testid="events-empty-state"] (title/text)',
      expectedBehavior: "Empty-state heading/body text change to the edited value.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- listing: closingCta (shared shape with Home/About) --------------
    {
      pageKey: "events",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].label/.title/.text',
      fieldPurpose: "Closing \"Would you like to host at RORUM?\" eyebrow/title/paragraph",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx getData() closingEyebrow/closingTitle/closingText",
      component: 'components/ui.tsx CTASection (variant="host")',
      frontendSelector: '[data-testid="events-closing-cta"]',
      expectedBehavior: "Label/H2/paragraph change to the edited values.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].actions[actionKey="main"].label/.href',
      fieldPurpose: '"Host at RORUM" closing button — text and destination',
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx getData() closingLabel, via lib/sanity-sections.ts getAction()",
      component: "components/ui.tsx CTASection",
      frontendSelector: '[data-testid="events-closing-cta"] a',
      expectedBehavior: "Button text and href both follow Sanity.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].items[itemKey="faqQuestion"/"faqLabel"].title',
      fieldPurpose: "Inline FAQ prompt question + link label",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "components/ui.tsx CTASection faqQuestion/faqLabel props",
      component: "components/ui.tsx CTASection",
      frontendSelector: ".faq-inline-prompt",
      expectedBehavior: "FAQ prompt question/link text change.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Reuses the existing shared Home/About \"Closing CTA FAQ prompt row\" ITEM_ROLE_RULES entry — same sectionKey, no Events-specific rule needed.",
    },

    // ---- listing: SEO ------------------------------------------------------
    {
      pageKey: "events",
      sectionKey: "seo",
      sanityPath: "seo.title / seo.description / seo.ogImage",
      fieldPurpose: "Search Result Title / Description / Social Sharing Image for the Events listing page",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: LISTING_QUERY,
      mapper: "events/page.tsx generateMetadata() -> localizedPageMetadata()",
      component: "events/page.tsx generateMetadata()",
      frontendSelector: 'head > title, head meta[name="description"], head meta[property="og:image"]',
      expectedBehavior: "Meta title/description/og:image reflect page-events.seo, per locale, falling back to the existing hardcoded defaults when empty.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Fixed this pass: generateMetadata() previously read description from the legacy, unpublished `eventsPage` " +
        "document (always null in production) and never read seo.ogImage or seo.title at all. Now reads " +
        "page-events.seo directly, same pattern as Home/About.",
    },

    // ---- event: identity/routing -------------------------------------------
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "title",
      fieldPurpose: "Event name",
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "components/EventCard.tsx <h3>, events/[slug]/page.tsx <h1>",
      frontendSelector: 'EventCard h3; event-detail page h1',
      expectedBehavior: "Title text matches the edited value in the requested locale on card and detail page.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "slug.current",
      fieldPurpose: "Event's URL segment",
      fieldType: "rawString",
      required: true,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "components/LocaleLink.tsx (card link), events/[slug]/page.tsx (route param)",
      frontendSelector: "URL path /events/<slug>",
      expectedBehavior: "Card and detail page are reachable at /events/<slug>; slug is validated required + unique by Sanity.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Technical but operationally necessary — generated from the English title by default, editable, readOnly not applied so a deliberate correction remains possible.",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "image / image.alt",
      fieldPurpose: "Banner image + alt text",
      fieldType: "image",
      required: true,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "EventCard.tsx (background-image, aria-hidden), events/[slug]/page.tsx (next/image, alt=imageAlt)",
      frontendSelector: "EventCard background; event-detail hero <img>",
      expectedBehavior: "Photo used everywhere the event appears; alt text is announced on the detail-page hero image (the card itself uses the photo as a pure CSS background and does not expose alt text — see notes).",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "image.alt is genuinely used on the Event Detail hero (next/image alt prop), so it stays required — unlike " +
        "Home's quickPaths/servicesTeaser decorative images. EventCard's own background-image approach means the " +
        "same alt text is never announced on the card itself; this is a pre-existing component-level accessibility " +
        "characteristic, not a CMS wiring defect, and is out of this pass's scope (would require changing " +
        "EventCard's markup, a visual/component change).",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "date / time / address / language / duration",
      fieldPurpose: "Date, time range, address, spoken language, and duration",
      fieldType: "rawString",
      required: true,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: `${MAPPER}; lib/eventDuration.ts formatDuration; lib/eventLanguage.ts getEventLanguageLabel`,
      component: "EventCard.tsx (date/time badge), events/[slug]/page.tsx InfoGridItem/DetailRow",
      frontendSelector: "event card date badge; detail-page info grid + Practical Information rows",
      expectedBehavior: "Date/time/address/language/duration render exactly as stored, locale-aware formatting applied for date/duration/language label only (values themselves are not translated, per the localization model).",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "duration.value has validation greaterThan(0); date/time/address are required, language is optional (options list only, no validation).",
    },

    // ---- event: ticket information ------------------------------------------
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "price",
      fieldPurpose: "Price string, e.g. \"295 kr.\" or \"Free\"",
      fieldType: "rawString",
      required: false,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "events/[slug]/page.tsx InfoGridItem (Ticket icon)",
      frontendSelector: "detail-page info grid, price cell",
      expectedBehavior: "Price renders exactly as stored.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Not rendered on EventCard at all (grep-confirmed) — only on the Event Detail page.",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "ticketUrl / ticketButtonLabel",
      fieldPurpose: "Ticket purchase link + optional button text override",
      fieldType: "link",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "events/[slug]/page.tsx TicketButton",
      frontendSelector: "detail-page Buy Ticket button",
      expectedBehavior:
        "isSoldOut=true -> disabled \"Sold Out\" button (ticketUrl irrelevant); isSoldOut=false + no ticketUrl -> " +
        "disabled \"Ticket link coming soon\"; isSoldOut=false + ticketUrl set -> active link, using ticketButtonLabel " +
        "when set, else the shared \"Buy Ticket\" default.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Precedence rule (documented + tested this pass, unchanged behavior): isSoldOut is the sole gate — ticketsLeft is never consulted by this button. See ticketsLeft entry below.",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "ticketProviderInfo.label / .value",
      fieldPurpose: "Display-only \"Ticket provider\" row label + provider name",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: `${MAPPER}; events/[slug]/page.tsx resolveTicketProviderLabel()`,
      component: "events/[slug]/page.tsx DetailRow (Practical Information)",
      frontendSelector: "detail-page Practical Information, Ticket provider row",
      expectedBehavior: "Per-event label overrides the shared eventMessages label when set (5-tier priority: event exact-locale -> shared exact-locale -> event English -> shared English -> code default); value renders the provider name.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "ticketsLeft",
      fieldPurpose: "Number of tickets remaining",
      fieldType: "number",
      required: false,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "EventCard.tsx availability badge, events/[slug]/page.tsx availability DetailRow",
      frontendSelector: "card availability text; detail-page availability row",
      expectedBehavior: '0 is a valid, distinct value (min(0) validation) and renders "0 spot(s) left" — it does NOT disable the ticket button (see ticketUrl/isSoldOut entries). isSoldOut always wins over ticketsLeft when both are set: this is the defined, tested precedence rule, left unchanged per explicit decision.',
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Manually editable today (not Billetto-synced) and continues to work exactly as before — no logic change made this pass.",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "isSoldOut",
      fieldPurpose: "Marks the event as sold out",
      fieldType: "boolean",
      required: false,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "EventCard.tsx, events/[slug]/page.tsx TicketButton + availability row + hero desaturation",
      frontendSelector: "card sold-out badge; detail-page Sold Out button/badge/desaturated hero",
      expectedBehavior: "true unconditionally shows the sold-out state everywhere the event appears and disables the ticket button, regardless of ticketsLeft.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "calendarUrl / waitlistUrl / included",
      fieldPurpose: "Add-to-calendar link, waitlist link, \"What's included\" bullet list",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: `${MAPPER} (all 3 are read and passed through to the RorumEvent shape)`,
      component: "n/a — not rendered by any component",
      frontendSelector: "n/a — not rendered anywhere",
      expectedBehavior: "n/a — grep-confirmed zero rendering consumers site-wide.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "technical-hidden",
      notes:
        "FIXED this pass (approved decision): hidden in Studio rather than wired to new UI, since rendering them " +
        "would be new visible page content, out of this pass's \"no visual redesign\" scope. Underlying data (if " +
        "any) is preserved, not deleted — same treatment as event.ts's existing legacy hidden fields.",
    },

    // ---- event: content ------------------------------------------------------
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "longDescription",
      fieldPurpose: "Full event overview shown on the detail page",
      fieldType: "i18nText",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "events/[slug]/page.tsx Event Overview <p>",
      frontendSelector: 'heading "Event Overview" ~ p',
      expectedBehavior: "Overview paragraph matches the edited value, falling back to a hardcoded default when empty.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "whatToExpect",
      fieldPurpose: '"What to Expect" bullet list',
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: `${MAPPER} — splits on \\r?\\n into ordered bullets, filters blank lines`,
      component: "events/[slug]/page.tsx What to Expect <ul>",
      frontendSelector: 'heading "What to Expect" ~ ul li',
      expectedBehavior: "Bullets render in the exact line order stored, falling back to a hardcoded 5-line default when empty.",
      mutationStrategy: "rich-text-insert",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Order is preserved by the newline-split itself (no separate array-key reordering needed) — one text field, not a Sanity array.",
    },
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "arrival",
      fieldPurpose: "Arrival note",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "events/[slug]/page.tsx DetailRow (Practical Information, Arrival row)",
      frontendSelector: "detail-page Practical Information, Arrival row",
      expectedBehavior: "Arrival text matches the edited value, falling back to a hardcoded default when empty.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- event: share controls -----------------------------------------------
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "shareSettings[].type / .enabled / .label",
      fieldPurpose: "Which share actions appear, in what order, enabled/disabled, and their accessible label",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: MAPPER,
      component: "components/EventShare.tsx",
      frontendSelector: "detail-page Share with Friends row",
      expectedBehavior: "Array order = display order; enabled=false hides that action without removing it; label is the accessible (screen-reader) name.",
      mutationStrategy: "reorder",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Share URLs themselves (WhatsApp/email/LinkedIn/Facebook/copy-link/Instagram) are always built in code from " +
        "the event's own current page URL (components/EventShare.tsx) — there is no manager-entered URL field for " +
        "any of these, matching the task's explicit requirement not to allow arbitrary manager URLs here. `type` is " +
        "a fixed enum (7 known values) and correctly not manager-extensible.",
    },

    // ---- event: SEO ------------------------------------------------------
    {
      pageKey: "events",
      sectionKey: "seo",
      sanityPath: "seo.title / seo.description / seo.ogImage",
      fieldPurpose: "Per-event Search Result Title / Description / Social Sharing Image",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: EVENT_QUERY,
      mapper: "events/[slug]/page.tsx generateMetadata()",
      component: "events/[slug]/page.tsx generateMetadata()",
      frontendSelector: 'head > title, head meta[name="description"], head meta[property="og:image"]',
      expectedBehavior: "Meta title/description/og:image prefer this event's own seo fields, falling back to event.title/.longDescription/.image when empty.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Fixed this pass: generateMetadata() previously built title/description/image exclusively from " +
        "event.title/.longDescription/.image and never read event.seo at all — an editor filling in an event's SEO " +
        "block had zero effect on that event's actual search-result/share-preview appearance.",
    },

    // ---- event: legacy fields ---------------------------------------------
    {
      pageKey: "events",
      sectionKey: "event",
      sanityPath: "shortDescription / practicalDetails / ticketProvider",
      fieldPurpose: "Superseded fallback fields kept for already-migrated documents",
      fieldType: "repeatable",
      required: false,
      languages: [],
      querySource: EVENT_QUERY,
      mapper: "lib/sanityEvents.ts getLegacyDetail() — fallback only, when the new field is empty",
      component: "n/a",
      frontendSelector: "n/a — never directly rendered, only feeds a fallback chain",
      expectedBehavior: "Unconditionally hidden (`hidden: () => true`), no validation attached — cannot block publishing.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "technical-hidden",
      notes: "Confirmed by reading the full schema file: no `validation` rule exists on any of the 3 — the hidden-but-validated defect class does not reproduce here.",
    },

    // ---- eventMessages (cross-document-shared) -----------------------------
    {
      pageKey: "events",
      sectionKey: "eventMessages",
      sanityPath: "labels[key==<one of 22 known keys>].value",
      fieldPurpose: "Shared UI microcopy for every event card + detail page (headings, ticket-state labels, share strings)",
      fieldType: "keyedString",
      required: false,
      languages: ALL,
      querySource: MESSAGES_QUERY,
      mapper: "lib/sanity-i18n.ts pickLabel(); events/page.tsx eventCardMessages; events/[slug]/page.tsx getEventMessages()",
      component: "EventCard.tsx, events/[slug]/page.tsx (headings, TicketButton, availability row, EventShare)",
      frontendSelector: "varies per key — see notes",
      expectedBehavior: "Each of the 22 keys' trilingual text is used wherever that key is referenced, falling back to a hardcoded per-locale default when a key/language is missing.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Single document, no draft, all 22 expected keys present, no duplicates (verified live). `key` itself is " +
        "readOnly + labeled \"(do not change)\" (keyedString.ts) — already correctly technical-visible, not a defect.",
    },
  ],
};
