import type { StudioVisibilityContract, StudioVisibilityEntry } from "./studio-visibility-types";

/**
 * Home Studio Visibility Contract — the reverse-direction companion to
 * lib/content-contracts/home.ts. That contract already proved every
 * CONNECTED field renders correctly; this one instead starts from every
 * field a content manager actually SEES in Studio for page-home and asks
 * whether it has a real, documented purpose. Retrofit pass — no Home
 * migrations or frontend-connection work is repeated here.
 *
 * Verified against the LIVE page-home document (raw perspective, read-only)
 * plus direct inspection of pageSection.ts's FIELD_VISIBILITY /
 * SETTINGS_HIDDEN_FOR_SECTION_KEYS, contentItem.ts's hiddenForTrustBadge,
 * mediaItem.ts's isHomeDecorativeBackgroundMedia, and every
 * `localizedPageMetadata()` call site (to check `seo.ogImage` usage
 * site-wide, not just on Home).
 *
 * UPDATED after the approved implementation pass: every entry below
 * reflects current, post-fix reality. Fixed: eventsStrip's text/media/items
 * hidden + an in-Studio notice explaining event cards live in Events;
 * quickPaths icon now wired (value hidden); every audited item role's
 * unused sub-fields hidden (contentItem.ts's ITEM_ROLE_RULES, which also
 * replaced hiddenForTrustBadge — same behavior, more general mechanism);
 * ctaAction.linkType and mediaItem.caption hidden site-wide. Deferred,
 * unchanged: seo.ogImage, seo.title/description population, and the
 * pageSection.settings field-removal decision.
 */

const D: readonly ["en", "da", "uk"] = ["en", "da", "uk"];
const doc = "page-home";
const page = "home";
const q = "sanity/queries/page.ts:pageByKeyQuery";

function entry(e: Omit<StudioVisibilityEntry, "pageKey" | "documentId">): StudioVisibilityEntry {
  return { pageKey: page, documentId: doc, ...e };
}

export const homeStudioVisibilityContract: StudioVisibilityContract = {
  pageKey: page,
  documentId: doc,
  entries: [
    // ============================================================ hero
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].label`,
      studioTitle: "Small label", studioDescription: "Small eyebrow text above the title, e.g. \"Catering\".",
      fieldType: "i18n string", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "Sets the small eyebrow above the hero H1.",
      websiteConsumer: "Hero eyebrow text (HomeHero label prop)", querySource: q,
      mapper: "app/[locale]/(site)/page.tsx:getData (heroLabel)", component: "HomeHero SectionLabel",
      frontendSelectorOrConsumer: `page.getByTestId("home-hero-label")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized, label is plain English.",
      sharedSchemaImpact: "n/a — evaluated per-section already.", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].title`,
      studioTitle: "Title", studioDescription: "(none set at the field level — generic 'Title')",
      fieldType: "i18n string", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "The page's H1.", websiteConsumer: "H1 heading", querySource: q,
      mapper: "getData (heroTitle)", component: "HomeHero <h1>", frontendSelectorOrConsumer: `page.getByRole("heading", { level: 1 })`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].text`,
      studioTitle: "Text", studioDescription: "(generic)", fieldType: "i18n text",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "Hero intro paragraph.",
      websiteConsumer: "Hero paragraph under the H1", querySource: q, mapper: "getData (heroText)",
      component: "HomeHero <p>", frontendSelectorOrConsumer: `page.getByTestId("home-hero-text")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].media[_key=="heroVideo"].kind/videoFile`,
      studioTitle: "Type / Video file", studioDescription: "\"Photo or Video\" radio, then the matching upload field.",
      fieldType: "string + file", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "Chooses and uploads the hero background (currently a video).",
      websiteConsumer: "Hero background <video>/CSS background-image", querySource: q,
      mapper: "getData (heroImageUrl/heroVideoUrl, urlForFile/urlForImage)", component: "HomeHero",
      frontendSelectorOrConsumer: `page.locator(".home-hero-video")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Populated, renders correctly.",
      sharedSchemaImpact: "mediaItem is reused by every section's media[] site-wide — kind/videoFile/image/posterImage visibility is already conditional on kind, correctly.", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].media[_key=="heroVideo"].alt`,
      studioTitle: "Alt text", studioDescription: "Describes the photo/video for screen readers.",
      fieldType: "i18n string", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "n/a — deliberately hidden: the hero background is a decorative CSS background-image with no role=\"img\"/aria-label anywhere in HomeHero.",
      websiteConsumer: "(none — decorative)", querySource: q, mapper: "n/a",
      component: "n/a", frontendSelectorOrConsumer: "accessibility: confirmed no role/aria-label on the hero background in HomeHero (components/ui.tsx)",
      classification: "correctly-hidden", recommendedAction: "Keep hidden. Informational only: the field already holds real EN/DA/UK text from before this field was hidden — harmless orphaned data (not shown, not read), no action needed.",
      reason: "isHomeDecorativeBackgroundMedia (mediaItem.ts) hides this narrowly for hero+communityTeaser media on page-home only.",
      sharedSchemaImpact: "Narrowly scoped by document._id + sectionKey — verified it does not affect any other page's media alt field.", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].media[_key=="heroVideo"].caption`,
      studioTitle: "Caption", studioDescription: "Optional visible caption.",
      fieldType: "i18n text", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: true, requiredLanguages: [],
      editorialPurpose: "n/a — hidden site-wide (Approved Fix 6).",
      websiteConsumer: "(none)", querySource: q, mapper: "none — `.caption` is not referenced in any .ts/.tsx file site-wide (grep-verified)",
      component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass: mediaItem.caption hidden unconditionally, site-wide. Confirmed via a read-only query across all 12 page documents (published+draft) that no caption value was populated anywhere before hiding.",
      reason: "mediaItem.caption has zero frontend consumers anywhere in the codebase, now hidden everywhere.",
      sharedSchemaImpact: "Global — every section's media[] on every page.", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].actions[actionKey=="primary"/"secondary"]`,
      studioTitle: "Button text / Destination / Open in a new tab / Shown on the site",
      studioDescription: "Standard ctaAction fields.", fieldType: "i18n string + string + boolean + boolean",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
      localized: true, requiredLanguages: D, editorialPurpose: "The 2 hero CTA buttons (Host at RORUM / Attend Events).",
      websiteConsumer: "Hero primary/secondary buttons", querySource: q,
      mapper: "getData (resolveAction, lib/sanity-sections.ts)", component: "Button",
      frontendSelectorOrConsumer: `page.getByTestId("home-hero-primary-cta" | "home-hero-secondary-cta")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "label/href/openInNewTab/enabled all wired via the shared resolveAction() helper.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].actions[*].linkType`,
      studioTitle: "Link type", studioDescription: "Internal page / External website / Anchor on this page (radio).",
      fieldType: "string enum", editorVisibleExpected: false, editorVisibleActual: true,
      requiredExpected: false, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "Appears to classify the link, but has no effect.",
      websiteConsumer: "(none)", querySource: q,
      mapper: "resolveAction() deliberately does not branch on linkType — LocaleLink infers internal-vs-external purely from the href's own shape",
      component: "n/a", frontendSelectorOrConsumer: "none — documented in lib/sanity-sections.ts's resolveAction() comment",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass: ctaAction.linkType hidden unconditionally, site-wide (every button on every page, not just Home). Field and stored values preserved, not deleted.",
      reason: "An editor choosing \"External website\" reasonably expected that to do something; it never did — now hidden instead.",
      sharedSchemaImpact: "Every ctaAction on every page shares this exact field — global fix applied once.", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].items[itemKey=~"^trust"].icon/title`,
      studioTitle: "Icon / Title", studioDescription: "Icon picker + optional heading.",
      fieldType: "string + i18n string", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "The 4 trust badges (\"Up to 12 guests\", etc.) in the strip under the hero.",
      websiteConsumer: "Hero trust-badge strip", querySource: q, mapper: "getData (heroTrustItems)",
      component: "HomeHero trust list", frontendSelectorOrConsumer: `page.getByTestId("home-hero-trust-trust0..3")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized, all 4 populated.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "hero", sectionKind: "hero", fieldPath: `sections[sectionKey=="hero"].items[itemKey=~"^trust"].itemKey/text/image/href/label/value`,
      studioTitle: "(6 fields, all hidden)", studioDescription: "n/a — not shown for trust badges.",
      fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "n/a — these 6 generic contentItem fields don't apply to a trust badge.",
      websiteConsumer: "(none)", querySource: q, mapper: "n/a", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "Keep as-is — this is the model other sections' unused item fields (see below) should follow.",
      reason: "contentItem.ts's hiddenForTrustBadge() already scopes this narrowly to itemKey trust0-3.",
      sharedSchemaImpact: "Scoped to itemKey, not sectionKind — provably doesn't affect any other item anywhere.", approvalRequired: false,
    }),

    // ======================================================= quickPaths
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].label`,
      studioTitle: "Small label", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "Eyebrow above the Quick Paths heading.",
      websiteConsumer: "SectionHeader label", querySource: q, mapper: "getData (quickPathsLabel)",
      component: "SectionHeader", frontendSelectorOrConsumer: `page.getByTestId("home-quickpaths-label")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].title`,
      studioTitle: "Title", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "\"Start with what you need.\" heading.",
      websiteConsumer: "SectionHeader title", querySource: q, mapper: "getData (quickPathsTitle)",
      component: "SectionHeader", frontendSelectorOrConsumer: `page.getByRole("heading", { level: 2 })`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].items[*].itemKey`,
      studioTitle: "Key (do not change)", studioDescription: "Only present (and locked) on built-in items the website looks up by key.",
      fieldType: "readOnly string", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: true, localized: false, requiredLanguages: [],
      editorialPurpose: "Technical lookup key (events/hostAtRorum/catering/eventDecoration) — the editor cannot usefully act on it, only observe it.",
      websiteConsumer: "getItem()/positional lookup in getData", querySource: q, mapper: "getSection/items lookup",
      component: "n/a", frontendSelectorOrConsumer: "none (build-time lookup only)",
      classification: "technical-visible", recommendedAction: "Low priority — already readOnly with a clear \"(do not change)\" label and description. Could additionally be hidden entirely (editors never need to see it, only not-break it) but current handling is defensible.",
      reason: "A raw system key is exposed, even though it's locked and labeled.",
      sharedSchemaImpact: "Same pattern used by every itemKey/actionKey site-wide — consistent, not a Home-specific issue.", approvalRequired: true,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].items[*].icon`,
      studioTitle: "Icon", studioDescription: "Optional icon — search by name.",
      fieldType: "string (icon picker)", editorVisibleExpected: false, editorVisibleActual: true,
      requiredExpected: false, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "Lets the editor choose/replace the card's icon.", websiteConsumer: "QuickPathCard icon (wired this pass)",
      querySource: q, mapper: "getData (quickPathsFromSections: item.icon -> getIconCardIcon, falling back to the fixed per-href lookup when empty or invalid)",
      component: "QuickPathCard", frontendSelectorOrConsumer: `page.locator(".quick-path-card-*") svg`,
      classification: "visible-connected", recommendedAction: "FIXED this pass (Approved Fix 3): wired into QuickPathCard, with the original hardcoded lookup preserved as the fallback for empty/invalid values. A dry-run-only backfill migration (scripts/backfill-quickpath-icons.ts) is ready and reported separately — NOT run live. The \"hostAtRorum\" item's pre-existing icon:\"AlarmClock\" (which now genuinely renders, unlike before) and a newly-discovered \"catering\" conflict (icon:\"CalendarDays\" on the draft) were flagged as CONFLICTS by the dry-run, not auto-resolved — see the migration report.",
      reason: "Now genuinely affects the frontend; previously an editor's value here (AlarmClock) had silently done nothing.",
      sharedSchemaImpact: "contentItem.icon is used the same way it always was elsewhere (trust badges, editorial features) — no change to those.", approvalRequired: false,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].items[*].title/text/href/image/label`,
      studioTitle: "Title / Text / Link destination / Image / Link text", studioDescription: "generic",
      fieldType: "mixed", editorVisibleExpected: true, editorVisibleActual: true,
      requiredExpected: true, requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "Card title, description, destination, photo, and CTA label for each of the 4 quick-path cards.",
      websiteConsumer: "QuickPathsGrid cards", querySource: q, mapper: "getData (quickPathsFromSections)",
      component: "QuickPathCard", frontendSelectorOrConsumer: `page.locator(".quick-path-card-*")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "All 5 fields wired and populated; href is validated against isQuickPathHref with a safe fallback.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].items[*].image.alt`,
      studioTitle: "Alt text (nested inside Image)", studioDescription: "n/a — hidden for this role specifically.",
      fieldType: "i18n string", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: [],
      editorialPurpose: "n/a — the card photo is a pure CSS background-image with aria-hidden=\"true\" (QuickPathCard, app/shared.tsx); no accessible name is ever exposed for it.",
      websiteConsumer: "(none — decorative)", querySource: q, mapper: "not read", component: "n/a", frontendSelectorOrConsumer: "accessibility: verified aria-hidden on .quick-card-media",
      classification: "correctly-hidden",
      recommendedAction: "FIXED this pass: imageWithAlt.ts's alt field is now hidden (and its validation skipped) specifically when nested inside a quickPaths/servicesTeaser card item on page-home — scoped by document + sectionKey + itemKey pattern via a path-based lookup, mirroring mediaItem.ts's isHomeDecorativeBackgroundMedia. The `image` field itself (the actual photo) stays visible and required — only the unused alt subfield is hidden. Every other imageWithAlt usage site-wide (About's atmosphere photos, editorial feature images, etc.) is unaffected.",
      reason: "An editor's alt text here previously had zero effect but was presented as if it mattered.",
      sharedSchemaImpact: "Scoped narrowly by document (page-home) + sectionKey (\"quickPaths\") + itemKey pattern — no other page or item role affected.", approvalRequired: false,
    }),
    entry({
      sectionKey: "quickPaths", sectionKind: "quickPaths", fieldPath: `sections[sectionKey=="quickPaths"].items[*].value`,
      studioTitle: "Raw value (not translated)", studioDescription: "Only for values that shouldn't be translated, e.g. a bank account number.",
      fieldType: "string", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "n/a for a quick-path card — hidden (Approved Fix 3).", websiteConsumer: "(none)", querySource: q,
      mapper: "not read for quickPaths items", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (role \"Home quick-path card\") — explicitly requested alongside the icon fix.",
      reason: "Generic field with no meaning in this context, now hidden.",
      sharedSchemaImpact: "contentItem.value remains genuinely used elsewhere (e.g. FAQ/bank-detail rows) — scoped hide, no effect there.", approvalRequired: false,
    }),

    // ======================================================= eventsStrip
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].label`,
      studioTitle: "Small label", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "\"What's on\" eyebrow.",
      websiteConsumer: "SectionHeader label", querySource: q, mapper: "getData (eventsLabel)",
      component: "SectionHeader", frontendSelectorOrConsumer: `page.getByTestId("home-events-label")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].title`,
      studioTitle: "Title", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "\"Upcoming events at RORUM\" heading.",
      websiteConsumer: "SectionHeader title", querySource: q, mapper: "getData (eventsTitle)",
      component: "SectionHeader", frontendSelectorOrConsumer: `page.getByRole("heading", { level: 2 })`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].text`,
      studioTitle: "Text", studioDescription: "generic — \"Optional longer text\"",
      fieldType: "i18n text", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: true, requiredLanguages: [],
      editorialPurpose: "n/a — hidden (Approved Fix 2).",
      websiteConsumer: "(none)", querySource: q,
      mapper: "getData never destructures eventsStripSection.text", component: "n/a (no <p> is rendered for eventsStrip at all)",
      frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass: added to pageSection.ts's SECTION_FIELD_FORCE_HIDDEN map (fieldName \"text\" -> sectionKey \"eventsStrip\"), same mechanism eventsStrip.settings already used. Verified for both page-home and drafts.page-home via a dedicated schema-callback test. FIXED (later pass): drafts.page-home's text had a single stray, valueless `en` entry (pre-dating this hide) that failed allOrNothingLanguages() despite being invisible. pageSection.ts's label/title/text validation now skips whenever fieldHidden() would hide that same field (mirrors contentItem.ts's fix for item-level fields), and the stray entry was unset live via scripts/repair-home-about-validation.ts.",
      reason: "Was empty in production and had no code path that would ever render it even if filled in.",
      sharedSchemaImpact: "Scoped by sectionKey \"eventsStrip\" only — any other future \"custom\"-kind section still shows text normally.", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].media`,
      studioTitle: "Photos / video", studioDescription: "generic", fieldType: "array<mediaItem>",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "n/a — hidden (Approved Fix 2). Event cards are photographs from separate Event documents, not from this section.",
      websiteConsumer: "(none)", querySource: q, mapper: "not read for eventsStrip", component: "n/a",
      frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass — same SECTION_FIELD_FORCE_HIDDEN mechanism as text above.",
      reason: "Was empty; would have had no effect even if populated.",
      sharedSchemaImpact: "Scoped by sectionKey \"eventsStrip\" — \"custom\" sectionKind still shows media by default elsewhere.", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].items`,
      studioTitle: "Items", studioDescription: "generic", fieldType: "array<contentItem>",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "n/a — hidden (Approved Fix 2). Was easily mistaken for \"add an event card here\".",
      websiteConsumer: "(none)", querySource: q, mapper: "not read for eventsStrip", component: "n/a",
      frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass — same mechanism as text/media above. This was the field most likely to actively mislead an editor (the section visually IS a card list), now resolved.",
      reason: "Event cards come exclusively from separate `event` documents, never from anything stored here.",
      sharedSchemaImpact: "Scoped by sectionKey \"eventsStrip\" only.", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].label (Studio-only in-form notice)`,
      studioTitle: "Small label (wrapped)", studioDescription: "A Card/Text banner rendered above the label field, only for sectionKey \"eventsStrip\", explaining: \"Event cards shown here are managed in the separate Events section. This section controls only the heading and the 'View all events' button.\"",
      fieldType: "n/a — presentation only, no stored field/attribute", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "Tells a non-technical editor, in place, that this section's visible cards are managed elsewhere, before they scroll past label/title looking for them.",
      websiteConsumer: "Event cards render from separate `event` documents entirely, matched to this slot only by position/section order, not by any field stored here.",
      querySource: "sanity/queries/events.ts:allEventsQuery", mapper: "app/[locale]/(site)/page.tsx:getData (eventsPromise, sanityEventToRorumEvent)",
      component: "EventList (frontend) / sanity/components/EventsStripLabelField.tsx (Studio notice)", frontendSelectorOrConsumer: `page.locator(".event-section-head").locator("xpath=following-sibling::*[1]")`,
      classification: "conditional-dynamic", recommendedAction: "FIXED this pass (Approved Fix 2): implemented as a `components.field` wrapper on pageSection's existing `label` field (sanity/components/EventsStripLabelField.tsx), using `useFormValue` to detect sectionKey==\"eventsStrip\" and render an info Card above the default input. Zero new schema field/attribute — every other section's label field renders unchanged. NOT verified in a live Studio browser session this pass (disclosed limitation) — see the manual smoke-test checklist.",
      reason: "Nothing in Studio previously told a non-technical editor that this section's visible cards are managed elsewhere.",
      sharedSchemaImpact: "Attached to the shared `label` field, but the banner only renders when sectionKey resolves to \"eventsStrip\" — every other section's label field is unaffected (same default renderer).", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].actions[actionKey=="viewAll"]`,
      studioTitle: "Button text / Destination / etc.", studioDescription: "generic",
      fieldType: "mixed", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
      localized: true, requiredLanguages: D, editorialPurpose: "\"View all events\" button.",
      websiteConsumer: "View-all button next to the events strip heading", querySource: q,
      mapper: "getData (resolveAction)", component: "Button", frontendSelectorOrConsumer: `page.getByTestId("home-events-view-all")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired via resolveAction().",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "eventsStrip", sectionKind: "custom", fieldPath: `sections[sectionKey=="eventsStrip"].settings`,
      studioTitle: "Advanced settings", studioDescription: "Rarely needed — small layout flags such as a visual variant.",
      fieldType: "array<sectionSetting>", editorVisibleExpected: false, editorVisibleActual: false,
      requiredExpected: false, requiredActual: false, localized: false, requiredLanguages: [],
      editorialPurpose: "n/a — deliberately hidden.", websiteConsumer: "(none — empty in production, no frontend code reads it for this section, per the schema's own comment)",
      querySource: q, mapper: "n/a", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "Keep as-is — already the correct, documented pattern.",
      reason: "SETTINGS_HIDDEN_FOR_SECTION_KEYS explicitly names eventsStrip with a clear code comment explaining why.",
      sharedSchemaImpact: "Scoped by sectionKey, doesn't affect any other section's settings visibility.", approvalRequired: false,
    }),

    // =========================================== editorial (both sections)
    ...(["editorialAttendEvents", "editorialHostAtRorum"] as const).flatMap((sectionKey): StudioVisibilityEntry[] => {
      const label = sectionKey === "editorialAttendEvents" ? "Attend Events" : "Host at RORUM";
      const testId = sectionKey === "editorialAttendEvents" ? "home-feature-attend" : "home-feature-host";
      return [
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].label/title/text`,
          studioTitle: "Small label / Title / Text", studioDescription: "generic", fieldType: "i18n string/text",
          editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
          localized: true, requiredLanguages: D, editorialPurpose: `${label} feature block eyebrow, title and intro line.`,
          websiteConsumer: `${label} eyebrow/title/intro`, querySource: q, mapper: "getData (resolveFeature)",
          component: "EditorialFeatureSection", frontendSelectorOrConsumer: `page.getByTestId("${testId}-eyebrow"/"-intro")`,
          classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
          sharedSchemaImpact: "n/a", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].media[0].image/alt`,
          studioTitle: "Photo / Alt text", studioDescription: "generic mediaItem fields", fieldType: "image + i18n string",
          editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
          localized: true, requiredLanguages: D, editorialPurpose: `The feature photo for ${label}, with a real, informative accessible description (NOT decorative — role="img" is set).`,
          websiteConsumer: `${label} feature image`, querySource: q, mapper: "getData (resolveFeature: urlForImage, pickLocalized(media.alt))",
          component: "EditorialFeatureSection", frontendSelectorOrConsumer: `page.getByTestId("${testId}-media")`,
          classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Migrated and verified this session — real Sanity asset, approved trilingual alt text, correctly NOT hidden (this image is meaningful, unlike hero/communityTeaser backgrounds).",
          sharedSchemaImpact: "n/a", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].media[0].caption`,
          studioTitle: "Caption", studioDescription: "generic", fieldType: "i18n text",
          editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
          localized: true, requiredLanguages: [], editorialPurpose: "n/a — hidden site-wide (Approved Fix 6).",
          websiteConsumer: "(none)", querySource: q, mapper: "none", component: "n/a", frontendSelectorOrConsumer: "none",
          classification: "correctly-hidden", recommendedAction: "FIXED this pass — same site-wide hide as hero.media.caption.",
          reason: "mediaItem.caption has zero consumers anywhere, now hidden everywhere.", sharedSchemaImpact: "Global — see hero.media.caption entry.", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].actions[actionKey=="cta"]`,
          studioTitle: "Button text / Destination / etc.", studioDescription: "generic", fieldType: "mixed",
          editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
          localized: true, requiredLanguages: D, editorialPurpose: `${label} CTA button.`,
          websiteConsumer: `${label} CTA button`, querySource: q, mapper: "getData (resolveAction)",
          component: "EditorialFeatureSection", frontendSelectorOrConsumer: `page.getByTestId("${testId}-cta")`,
          classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired via resolveAction().",
          sharedSchemaImpact: "n/a", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].items[itemKey=="description"].text`,
          studioTitle: "Text", studioDescription: "generic", fieldType: "i18n text",
          editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
          localized: true, requiredLanguages: D, editorialPurpose: `${label} longer description paragraph.`,
          websiteConsumer: `${label} description paragraph`, querySource: q, mapper: "getData (getItem(section,\"description\")?.text)",
          component: "EditorialFeatureSection", frontendSelectorOrConsumer: `page.getByTestId("${testId}-description")`,
          classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
          sharedSchemaImpact: "n/a", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].items[itemKey=="description"].itemKey/icon/title/image/href/label/value`,
          studioTitle: "(7 fields, all hidden)", studioDescription: "n/a — not shown for the description row",
          fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
          localized: false, requiredLanguages: [], editorialPurpose: "n/a for a plain description paragraph — hidden.",
          websiteConsumer: "(none)", querySource: q, mapper: "not read for the \"description\" item", component: "n/a",
          frontendSelectorOrConsumer: "none",
          classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (role \"Home editorial description\", visible:[\"text\"] only — itemKey hidden too, same treatment as trust badges since this is a fixed, non-extensible row, not an editor-addable list).",
          reason: "7 previously fully-editable, empty fields with no effect, now hidden.",
          sharedSchemaImpact: "Scoped by sectionKey (editorialAttendEvents/editorialHostAtRorum) + itemKey \"description\" together.", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].items[itemKey=~"^feature"].icon/title`,
          studioTitle: "Icon / Title", studioDescription: "generic", fieldType: "string + i18n string",
          editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
          localized: true, requiredLanguages: D, editorialPurpose: `The 4 feature bullets under the ${label} description.`,
          websiteConsumer: `${label} feature bullet list`, querySource: q, mapper: "getData (resolveFeature: featureItems, getIconCardIcon)",
          component: "EditorialFeatureSection", frontendSelectorOrConsumer: "feature bullet list items",
          classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized, icons resolve via getIconCardIcon (full Lucide set).",
          sharedSchemaImpact: "n/a", approvalRequired: false,
        }),
        entry({
          sectionKey, sectionKind: "editorial", fieldPath: `sections[sectionKey=="${sectionKey}"].items[itemKey=~"^feature"].itemKey/text/image/href/label/value`,
          studioTitle: "(6 fields per feature item, 24 total across the 4 items, all hidden)", studioDescription: "n/a",
          fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
          localized: true, requiredLanguages: [], editorialPurpose: "n/a for a feature bullet (icon + short title is all the layout supports) — hidden.",
          websiteConsumer: "(none)", querySource: q, mapper: "not read for feature items", component: "n/a",
          frontendSelectorOrConsumer: "none",
          classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (role \"Home editorial feature bullet\", visible:[\"icon\",\"title\"] only — itemKey hidden too).",
          reason: "6 fields x 4 items x 2 sections (attend + host) = 48 previously empty, functionless inputs, now hidden.",
          sharedSchemaImpact: "Scoped by sectionKey + itemKey pattern \"feature*\" — contentItem.text/image/href/label/value remain genuinely used elsewhere.", approvalRequired: false,
        }),
      ];
    }),

    // =================================================== servicesTeaser
    entry({
      sectionKey: "servicesTeaser", sectionKind: "servicesTeaser", fieldPath: `sections[sectionKey=="servicesTeaser"].label/title`,
      studioTitle: "Small label / Title", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "Services section eyebrow + heading.",
      websiteConsumer: "ServicesTeaserSection label/title", querySource: q, mapper: "getData (servicesLabel/servicesTitle)",
      component: "ServicesTeaserSection", frontendSelectorOrConsumer: `page.getByRole("heading", { level: 2 })`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "servicesTeaser", sectionKind: "servicesTeaser", fieldPath: `sections[sectionKey=="servicesTeaser"].items[*].title/text/label/href/image`,
      studioTitle: "Title / Text / Link text / Link destination / Image", studioDescription: "generic",
      fieldType: "mixed", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "The 2 service cards (Catering, Event Decoration).",
      websiteConsumer: "ServicesTeaserSection cards", querySource: q, mapper: "getData (servicesFromSections)",
      component: "ServicesTeaserSection", frontendSelectorOrConsumer: "service card grid",
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired and populated.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "servicesTeaser", sectionKind: "servicesTeaser", fieldPath: `sections[sectionKey=="servicesTeaser"].items[*].image.alt`,
      studioTitle: "Alt text (nested inside Image)", studioDescription: "n/a — hidden for this role specifically.",
      fieldType: "i18n string", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: [],
      editorialPurpose: "n/a — the card photo is a pure CSS background-image with aria-hidden=\"true\" (ServicesTeaserSection, components/HomeEditorialSections.tsx); no accessible name is ever exposed for it.",
      websiteConsumer: "(none — decorative)", querySource: q, mapper: "not read", component: "n/a", frontendSelectorOrConsumer: "accessibility: verified aria-hidden on the card's background span",
      classification: "correctly-hidden",
      recommendedAction: "FIXED this pass — same imageWithAlt.ts scoped hide as quickPaths' equivalent entry, applied here for servicesTeaser cards. The `image` field itself stays visible and required.",
      reason: "An editor's alt text here previously had zero effect but was presented as if it mattered.",
      sharedSchemaImpact: "Scoped narrowly by document (page-home) + sectionKey (\"servicesTeaser\") + itemKey pattern — no other page or item role affected.", approvalRequired: false,
    }),
    entry({
      sectionKey: "servicesTeaser", sectionKind: "servicesTeaser", fieldPath: `sections[sectionKey=="servicesTeaser"].items[*].itemKey/icon/value`,
      studioTitle: "(3 fields per item, 6 total, all hidden)", studioDescription: "n/a",
      fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "n/a for a service card (uses `image`, not `icon`) — hidden.",
      websiteConsumer: "(none)", querySource: q, mapper: "not read for servicesTeaser items", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (role \"Home service teaser card\", visible:[\"title\",\"text\",\"label\",\"href\",\"image\"] — itemKey hidden too here, unlike quickPaths/About items, since servicesTeaser's 2 cards are a fixed, non-extensible pair.",
      reason: "6 previously-unused fields (itemKey + icon + value x 2 items), now hidden.", sharedSchemaImpact: "Scoped by sectionKey \"servicesTeaser\" + itemKey.", approvalRequired: false,
    }),

    // =================================================== communityTeaser
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].label/title/text`,
      studioTitle: "Small label / Title / Text", studioDescription: "generic", fieldType: "i18n string/text",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "Community section eyebrow, heading, and paragraph.",
      websiteConsumer: "CommunityTeaserSection label/title/text", querySource: q,
      mapper: "getData (communityLabel/communityTitle/communityText)", component: "CommunityTeaserSection",
      frontendSelectorOrConsumer: `page.getByRole("heading", { level: 2 })`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].media[0].image`,
      studioTitle: "Photo", studioDescription: "generic", fieldType: "image",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
      localized: false, requiredLanguages: [], editorialPurpose: "Background photo for the community section.",
      websiteConsumer: "CommunityTeaserSection background", querySource: q, mapper: "getData (communityImageUrl)",
      component: "CommunityTeaserSection", frontendSelectorOrConsumer: `page.locator(".community-teaser-full")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Migrated and verified this session — real Sanity CDN asset.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].media[0].alt`,
      studioTitle: "Alt text", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "n/a — decorative background, no accessible name in the DOM.",
      websiteConsumer: "(none — decorative)", querySource: q, mapper: "n/a", component: "n/a",
      frontendSelectorOrConsumer: "accessibility: verified no role/aria-label on the community background",
      classification: "correctly-hidden", recommendedAction: "Keep hidden.", reason: "Same isHomeDecorativeBackgroundMedia rule as hero, applied deliberately this session; unlike hero, no orphaned alt data exists here (field was hidden before any value was entered).",
      sharedSchemaImpact: "Narrowly scoped — verified.", approvalRequired: false,
    }),
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].media[0].caption`,
      studioTitle: "Caption", studioDescription: "generic", fieldType: "i18n text",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: [], editorialPurpose: "n/a — hidden site-wide (Approved Fix 6).", websiteConsumer: "(none)",
      querySource: q, mapper: "none", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass — same site-wide hide.", reason: "No consumers anywhere, now hidden everywhere.",
      sharedSchemaImpact: "Global — see hero.media.caption.", approvalRequired: false,
    }),
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].items[*].href/label`,
      studioTitle: "Link destination / Link text", studioDescription: "generic", fieldType: "string + i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "The 3 community quick-link chips.",
      websiteConsumer: "CommunityTeaserSection links", querySource: q, mapper: "getData (communityLinksFromSections)",
      component: "CommunityTeaserSection", frontendSelectorOrConsumer: "community link chips",
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired and populated.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "communityTeaser", sectionKind: "communityTeaser", fieldPath: `sections[sectionKey=="communityTeaser"].items[*].itemKey/icon/title/text/image/value`,
      studioTitle: "(6 fields per item, 18 total across the 3 links, all hidden)", studioDescription: "n/a",
      fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: [], editorialPurpose: "n/a — these links only ever render href+label — hidden.",
      websiteConsumer: "(none)", querySource: q, mapper: "not read for communityTeaser items", component: "n/a",
      frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (role \"Home community quick link\", visible:[\"href\",\"label\"] only — itemKey hidden too).",
      reason: "18 previously-unused fields across the 3 community links, now hidden.", sharedSchemaImpact: "Scoped by sectionKey \"communityTeaser\".", approvalRequired: false,
    }),

    // ======================================================= closingCta
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].label/title/text`,
      studioTitle: "Small label / Title / Text", studioDescription: "generic", fieldType: "i18n string/text",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "Closing CTA eyebrow, heading, paragraph.",
      websiteConsumer: "CTASection eyebrow/title/text", querySource: q,
      mapper: "getData (closingEyebrow/closingTitle/closingText)", component: "CTASection",
      frontendSelectorOrConsumer: `page.getByTestId("home-closing-cta")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"]`,
      studioTitle: "Button text / Destination / Open in a new tab / Shown on the site", studioDescription: "generic",
      fieldType: "mixed", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: true,
      localized: true, requiredLanguages: D, editorialPurpose: "Closing CTA button.",
      websiteConsumer: "CTASection Button", querySource: q, mapper: "getData (resolveAction)",
      component: "CTASection", frontendSelectorOrConsumer: `page.getByTestId("home-closing-cta-cta")`,
      classification: "visible-connected", recommendedAction: "Keep as-is.", reason: "Correctly wired via resolveAction() — unlike About's closing CTA, Home never had this bug.",
      sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].actions[actionKey=="main"].linkType`,
      studioTitle: "Link type", studioDescription: "generic", fieldType: "string enum",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "n/a — hidden site-wide (Approved Fix 5).",
      websiteConsumer: "(none)", querySource: q, mapper: "not branched on", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass — same site-wide hide as hero.actions.linkType.",
      reason: "Duplicate instance of the site-wide ctaAction.linkType finding, now resolved once for every page.", sharedSchemaImpact: "Global.", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].items[itemKey=="faqQuestion"/"faqLabel"].title`,
      studioTitle: "Title", studioDescription: "generic", fieldType: "i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "FAQ inline prompt question + link label.",
      websiteConsumer: "FAQInlinePrompt", querySource: q, mapper: "getData (getItem)", component: "FAQInlinePrompt",
      frontendSelectorOrConsumer: "FAQ prompt near the CTA", classification: "visible-connected",
      recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.", sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].items[itemKey=~"^link"].href/label`,
      studioTitle: "Link destination / Link text", studioDescription: "generic", fieldType: "string + i18n string",
      editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: true, requiredActual: false,
      localized: true, requiredLanguages: D, editorialPurpose: "4 suggested-path chips.", websiteConsumer: "CTASection links",
      querySource: q, mapper: "getData (closingLinksFromSections)", component: "CTASection",
      frontendSelectorOrConsumer: "suggested-path chips", classification: "visible-connected",
      recommendedAction: "Keep as-is.", reason: "Fully wired, fully localized.", sharedSchemaImpact: "n/a", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].items[*].itemKey/icon/text/image/value (faqQuestion/faqLabel/link0-3, 6 items, all hidden)`,
      studioTitle: "(up to 6 fields per item, 36 total, all hidden)", studioDescription: "n/a",
      fieldType: "mixed", editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: true, requiredLanguages: [], editorialPurpose: "n/a for FAQ prompt rows or link chips — hidden.",
      websiteConsumer: "(none)", querySource: q, mapper: "not read", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden", recommendedAction: "FIXED this pass via ITEM_ROLE_RULES (roles \"Closing CTA FAQ prompt row\" and \"Closing CTA suggested-path link\", shared by Home + About) — itemKey hidden too here, same closed-set treatment as trust badges. FIXED (later pass): drafts.page-home's link0/link1/link2 title/text/image had each accumulated a stray, empty-string `en` entry from before this hide existed, which failed allOrNothingLanguages()/imageWithAlt validation despite being invisible — a hidden field silently blocking the draft from publishing, with no visible field to explain why. contentItem.ts's title/text/label validation and imageWithAlt.ts's alt validation now both skip whenever the field is hidden by an item role (one shared mechanism, contentItem.ts's matchItemRoleInContext, reused by both), so this class of bug can't recur. The 3 items' stray data was also unset live via scripts/repair-home-about-validation.ts (backed up first, dry-run verified, idempotent — see the migration report).",
      reason: "Same generic-contentItem-oversupply pattern repeated across every section on the page, now hidden.", sharedSchemaImpact: "Scoped by sectionKey \"closingCta\" + itemKey pattern — one shared rule covers both Home and About.", approvalRequired: false,
    }),
    entry({
      sectionKey: "closingCta", sectionKind: "cta", fieldPath: `sections[sectionKey=="closingCta"].settings`,
      studioTitle: "Advanced settings", studioDescription: "generic", fieldType: "array<sectionSetting>",
      editorVisibleExpected: false, editorVisibleActual: false, requiredExpected: false, requiredActual: false,
      localized: false, requiredLanguages: [], editorialPurpose: "n/a — hidden by the generic sectionKind mechanism (FIELD_VISIBILITY.cta does not include \"settings\").",
      websiteConsumer: "(none — <CTASection variant=\"final\"> is a hardcoded JSX literal; settings is never read via getSetting() anywhere on Home)",
      querySource: q, mapper: "n/a", component: "n/a", frontendSelectorOrConsumer: "none",
      classification: "correctly-hidden",
      recommendedAction: "CORRECTION relative to the About audit: settings is hidden here too (same as About's closingCta, also sectionKind \"cta\") — not visible as previously assumed for the equivalent About field. Informational: the stored value (\"final\") is genuinely dead data (hidden AND unread) but requires no urgent action since it's not misleading anyone. Recommend a later cleanup pass across all sections to confirm `settings`/getSetting() has zero real usage site-wide (grep-confirmed this session) and consider removing the mechanism, or documenting it as reserved-for-future-use.",
      reason: "This is currently hidden only as a side effect of FIELD_VISIBILITY.cta's field list, not a deliberate, documented choice the way eventsStrip's hide is — worth making that explicit in a comment.",
      sharedSchemaImpact: "settings has 0 confirmed consumers anywhere in app/ (grep-verified) — this is a genuinely site-wide finding, not page-specific.", approvalRequired: true,
    }),

    // ============================================================= seo
    entry({
      sectionKey: "seo", sectionKind: "n/a", fieldPath: `seo.title`,
      studioTitle: "SEO title", studioDescription: "Shown in the browser tab and search results. Keep under ~60 characters.",
      fieldType: "i18n string", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: false,
      requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "Sets the browser-tab title and search-result title.", websiteConsumer: "generateMetadata() -> <title>",
      querySource: q, mapper: "getData (seoTitle = pickLocalized(newPage?.seo?.title, locale) ?? fallback.seoTitle)",
      component: "app/[locale]/(site)/page.tsx:generateMetadata", frontendSelectorOrConsumer: "page.title()",
      classification: "visible-connected-but-empty",
      recommendedAction: "Wiring is correct and already verified this session (title fix, previous turn). Currently EMPTY in Sanity for all 3 languages — the hardcoded fallback \"RORUM | Creative Event Space in Copenhagen\" is what's actually live. Recommend populating via a small content pass (not a migration — direct Studio entry) once approved; not required before About/next-page work.",
      reason: "Empty-but-connected is not complete content — flagging per instruction rather than reporting this as done.",
      sharedSchemaImpact: "seo is the shared object type used by every page/event/singleton — populating Home's title doesn't affect any other document.", approvalRequired: false,
    }),
    entry({
      sectionKey: "seo", sectionKind: "n/a", fieldPath: `seo.description`,
      studioTitle: "SEO description", studioDescription: "Shown under the title in search results. Keep under ~160 characters.",
      fieldType: "i18n text", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: false,
      requiredActual: false, localized: true, requiredLanguages: D,
      editorialPurpose: "Sets the search-result/social-share description.", websiteConsumer: "generateMetadata() -> meta[name=description], og:description",
      querySource: q, mapper: "getData (description = pickLocalized(newPage?.seo?.description, locale) ?? fallback.description)",
      component: "app/[locale]/(site)/page.tsx:generateMetadata", frontendSelectorOrConsumer: `page.locator('meta[name="description"]')`,
      classification: "visible-connected-but-empty",
      recommendedAction: "Wiring fixed and verified this session. Currently EMPTY for all 3 languages in Sanity — live site shows the hardcoded fallback. Same recommendation as seo.title: populate later, not blocking.",
      reason: "Empty-but-connected, reported precisely per instruction.",
      sharedSchemaImpact: "Shared seo object — page-scoped population only.", approvalRequired: false,
    }),
    entry({
      sectionKey: "seo", sectionKind: "n/a", fieldPath: `seo.ogImage / seo.ogImage.alt`,
      studioTitle: "Social Sharing Image / Alt text", studioDescription: "The preview image shown when this page is shared on Facebook, LinkedIn, messaging apps, and other services.",
      fieldType: "image + i18n string", editorVisibleExpected: true, editorVisibleActual: true, requiredExpected: false,
      requiredActual: false, localized: true, requiredLanguages: [],
      editorialPurpose: "Lets the editor set the social-share preview image for Home.",
      websiteConsumer: "generateMetadata() -> og:image", querySource: q,
      mapper: "getData() ogImageUrl = urlForImage(newPage?.seo?.ogImage), passed to localizedPageMetadata()'s `image` param when set",
      component: "app/[locale]/(site)/page.tsx:generateMetadata", frontendSelectorOrConsumer: `page.locator('meta[property="og:image"]')`,
      classification: "visible-connected",
      recommendedAction: "FIXED this pass: Home's generateMetadata() now passes `image` through from seo.ogImage, reusing the same `image` param the event-detail page already used (lib/seo.ts's localizedPageMetadata). Also fixed a latent bug in that same helper: it unconditionally prefixed `image` with `siteUrl`, which silently produced a broken URL for any already-absolute image URL (e.g. a Sanity CDN asset) — now only relative paths get the prefix. Content (an uploaded ogImage) is optional and currently unset on Home; falls back to the existing hardcoded /images/hero.jpg exactly as before.",
      reason: "Now genuinely affects the frontend — an editor uploading a page-specific share image will see it used.",
      sharedSchemaImpact: "Wired only for Home + About's own generateMetadata() calls — no other page's call site was touched.", approvalRequired: false,
    }),
  ],
};
