import { locales } from "@/lib/i18n";
import type { PageContentContract } from "@/lib/content-contracts/types";

const ALL = locales; // ["en", "da", "uk"]
const QUERY = "sanity/queries/page.ts (pageByKeyQuery, pageKey=\"home\")";
const SECTIONS = "lib/sanity-sections.ts (getSection/getItem/resolveAction)";

/**
 * Home page content contract — pilot for the page-by-page CMS audit, kept
 * current through the Home CMS-connection fix pass. Sourced by reading
 * sanity/schemaTypes/documents/page.ts, sanity/schemaTypes/objects/{pageSection,contentItem,ctaAction,mediaItem}.ts,
 * lib/sanity-sections.ts, and every line of getData()/generateMetadata() in
 * app/[locale]/(site)/page.tsx, cross-checked against the live "page-home"
 * document (published, read-only fetch) and the Home visual-diff spec.
 *
 * `classification` reflects what the code + data actually do today — see
 * lib/content-contracts/types.ts's `FieldClassification` doc comment for
 * what each value means, in particular the difference between "connected"
 * (real content resolves through the wiring today) and
 * "pending-approved-migration" (wiring is done, data backfill is dry-run
 * only, awaiting approval).
 */
export const homeContract: PageContentContract = {
  pageKey: "home",
  documentId: "page-home",
  documentType: "page",
  entries: [
    // ---- hero ----------------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].label',
      fieldPurpose: "Small eyebrow label above the hero H1",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: `getData() heroLabel, via ${SECTIONS}`,
      component: "components/ui.tsx HomeHero (SectionLabel)",
      frontendSelector: '[data-testid="home-hero-label"]',
      expectedBehavior: "Text above the H1 changes to the edited value in the requested locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].title',
      fieldPurpose: "Hero H1",
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() heroTitle",
      component: "components/ui.tsx HomeHero (<h1>)",
      frontendSelector: '.home-hero-full h1 (role=heading level=1, unique on page)',
      expectedBehavior: "H1 text matches the edited value in the requested locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].text',
      fieldPurpose: "Hero intro paragraph",
      fieldType: "i18nText",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() heroText",
      component: "components/ui.tsx HomeHero (<p>)",
      frontendSelector: '[data-testid="home-hero-text"]',
      expectedBehavior: "Paragraph text matches the edited value in the requested locale.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].media[0].image | .videoFile',
      fieldPurpose: "Hero background image/video",
      fieldType: "video",
      required: true,
      languages: [],
      querySource: QUERY,
      mapper: "getData() heroImageUrl/heroVideoUrl, urlForImage/urlForFile (sanity/lib/image.ts)",
      component: "components/ui.tsx HomeHero (background-image + <video>)",
      frontendSelector: ".home-hero-full[style*=background-image], .home-hero-video[src]",
      expectedBehavior: "Swapping the uploaded photo or video changes the hero background asset URL.",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].media[0].alt',
      fieldPurpose: "Hero media alt text",
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "not read — intentionally, see notes",
      component: "components/ui.tsx HomeHero — no alt/aria-label prop exists",
      frontendSelector: "n/a — not rendered",
      expectedBehavior:
        "Field is hidden in Studio for Home's hero media specifically (sanity/schemaTypes/objects/mediaItem.ts's isHomeHeroBackgroundMedia), and its required-language validation is skipped for that same case — so it can no longer block publishing, and an editor is no longer shown a field that does nothing.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "technical-hidden",
      notes:
        "Scoped narrowly to document _id \"page-home\" (draft-stripped) + sectionKey \"hero\" — every other page's " +
        "hero media (11 of the site's other pages also use sectionKey \"hero\", e.g. About's has 3 media items) " +
        "keeps this field exactly as before. Background is CSS background-image (no alt) and the <video> is aria-hidden.",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].items[itemKey^="trust"].icon/.title',
      fieldPurpose: "4 hero trust badges (icon + short title)",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() heroTrustItems",
      component: "components/ui.tsx HomeHero (ul.home-hero-trust)",
      frontendSelector: '[data-testid^="home-hero-trust-"] (per item, keyed by itemKey)',
      expectedBehavior: "Icon and title of a trust badge change; badge count matches populated items.",
      mutationStrategy: "icon-swap",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].actions[actionKey=="primary"].label/.href/.linkType/.openInNewTab/.enabled',
      fieldPurpose: '"Host at RORUM" hero button — text and destination',
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() heroPrimaryAction, via lib/sanity-sections.ts resolveAction()",
      component: "app/[locale]/(site)/page.tsx <Button data-testid=\"home-hero-primary-cta\">",
      frontendSelector: '[data-testid="home-hero-primary-cta"]',
      expectedBehavior:
        "Button text and href both change to the edited values; openInNewTab=true renders target=_blank rel=\"noopener noreferrer\"; enabled=false renders no button at all.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "hero",
      sanityPath: 'sections[sectionKey=="hero"].actions[actionKey="secondary"].label/.href/.linkType/.openInNewTab/.enabled',
      fieldPurpose: '"Attend Events" hero button — text and destination',
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() heroSecondaryAction, via resolveAction()",
      component: 'app/[locale]/(site)/page.tsx <Button data-testid="home-hero-secondary-cta">',
      frontendSelector: '[data-testid="home-hero-secondary-cta"]',
      expectedBehavior: "Same behaviour as the primary hero action above.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- quickPaths ------------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "quickPaths",
      sanityPath: 'sections[sectionKey=="quickPaths"].label',
      fieldPurpose: '"Quick paths" section eyebrow',
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() quickPathsLabel",
      component: "components/ui.tsx SectionHeader",
      frontendSelector: '[data-testid="home-quickpaths-label"]',
      expectedBehavior: "Label text above the quick-paths title changes.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "quickPaths",
      sanityPath: 'sections[sectionKey=="quickPaths"].title',
      fieldPurpose: '"Quick paths" section title',
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() quickPathsTitle",
      component: "components/ui.tsx SectionHeader (<h2>)",
      frontendSelector: 'getByRole("heading", {level: 2, name: <quickPathsTitle>})',
      expectedBehavior: "Section H2 text changes.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "quickPaths",
      sanityPath: 'sections[sectionKey=="quickPaths"].items[itemKey=~"events|hostAtRorum|catering|eventDecoration"].title/.text/.image/.label/.href',
      fieldPurpose: "4 quick-path cards (title, text, image, link label, link destination)",
      fieldType: "repeatable",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() quickPaths[] — href now resolved via app/shared.tsx isQuickPathHref()",
      component: "app/shared.tsx QuickPathsGrid / QuickPathCard (.quick-path-card-<slug>, stable per item)",
      frontendSelector: '.quick-path-card-events / -host-at-rorum / -catering / -event-decoration',
      expectedBehavior:
        "Card title/text/image/link-label change per item; link destination now follows the item's own Sanity " +
        "href when it's one of the 4 known quick-path destinations, falling back safely to the positional default " +
        "otherwise (QuickPathCard looks up icon/tone by href — see isQuickPathHref).",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Fixed this pass: href previously always came from a hardcoded local array regardless of the item's own " +
        "Sanity href (see the disconnected-field report in the Home Content Audit). Still uses that array as a " +
        "fallback for an href that isn't one of the 4 recognized destinations — documented in " +
        "app/[locale]/(site)/page.tsx's quickPathMeta comment.",
    },

    // ---- eventsStrip -------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "eventsStrip",
      sanityPath: 'sections[sectionKey=="eventsStrip"].label',
      fieldPurpose: '"What\'s on" section eyebrow',
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() eventsLabel",
      component: "components/ui.tsx SectionHeader",
      frontendSelector: '[data-testid="home-events-label"]',
      expectedBehavior: "Label above the events strip title changes.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "eventsStrip",
      sanityPath: 'sections[sectionKey=="eventsStrip"].title',
      fieldPurpose: '"Upcoming events at RORUM" title',
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() eventsTitle",
      component: "components/ui.tsx SectionHeader (<h2>)",
      frontendSelector: 'getByRole("heading", {level: 2, name: <eventsTitle>})',
      expectedBehavior: "Section H2 text changes.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "eventsStrip",
      sanityPath: 'sections[sectionKey=="eventsStrip"].actions[actionKey="viewAll"].label/.href/.linkType/.openInNewTab/.enabled',
      fieldPurpose: '"View all events" button — text and destination',
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() eventsViewAllAction, via resolveAction()",
      component: 'app/[locale]/(site)/page.tsx <Button data-testid="home-events-view-all">',
      frontendSelector: '[data-testid="home-events-view-all"]',
      expectedBehavior: "Button text and href both follow Sanity; enabled=false hides the button.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "eventsStrip",
      sanityPath: 'sections[sectionKey=="eventsStrip"].settings',
      fieldPurpose: "Advanced settings (unused key/value rows)",
      fieldType: "keyedString",
      required: false,
      languages: [],
      querySource: QUERY,
      mapper: "not read by any Home code path",
      component: "n/a",
      frontendSelector: "n/a — hidden in Studio",
      expectedBehavior: "Field no longer shown to the editor for this section; stored values (none currently) untouched.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "hidden",
      classification: "technical-hidden",
      notes:
        "Hidden specifically for sectionKey \"eventsStrip\" via pageSection.ts's SETTINGS_HIDDEN_FOR_SECTION_KEYS — " +
        "any other \"custom\"-kind section elsewhere on the site keeps this field exactly as before.",
    },
    {
      pageKey: "home",
      sectionKey: "eventsStrip",
      sanityPath: "n/a — separate `event` documents",
      fieldPurpose: "The events shown in the horizontal strip",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: "sanity/queries/events.ts allEventsQuery",
      mapper: "lib/sanityEvents.ts sanityEventToRorumEvent",
      component: "components/EventCard.tsx EventList",
      frontendSelector: ".event-section-head ~ * [class*=event-card]",
      expectedBehavior: "Publishing/editing an `event` document changes the strip's contents.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes: "Cross-document composition — covered by the separate Event Details/listing contract, not duplicated here.",
    },

    // ---- editorialAttendEvents / editorialHostAtRorum ------------------
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].label/.title/.text',
      fieldPurpose: "Attend Events feature eyebrow/title/intro",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> attendFeature.{eyebrow,title,intro}",
      component: "components/HomeEditorialSections.tsx EditorialFeatureSection",
      frontendSelector: '[data-testid="home-feature-attend-eyebrow"], h2, [data-testid="home-feature-attend-intro"]',
      expectedBehavior: "Eyebrow/H2/intro paragraph change to the edited values.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].items[itemKey="description"].text',
      fieldPurpose: "Attend Events feature description paragraph",
      fieldType: "i18nText",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> attendFeature.description",
      component: "components/HomeEditorialSections.tsx EditorialFeatureSection",
      frontendSelector: '[data-testid="home-feature-attend-description"]',
      expectedBehavior: "Description paragraph changes to the edited value.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].items[itemKey^="feature"].title',
      fieldPurpose: "4 feature bullet labels",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> attendFeature.features[].label",
      component: "components/HomeEditorialSections.tsx EditorialFeatureSection (<ul><li>)",
      frontendSelector: '[data-testid="home-feature-attend-feature-feature0"] span (etc. per itemKey)',
      expectedBehavior: "Bullet text changes per item, addressed by stable itemKey.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].items[itemKey^="feature"].icon',
      fieldPurpose: "4 feature bullet icons",
      fieldType: "icon",
      required: false,
      languages: [],
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> item.icon via lib/iconCardIcons.ts getIconCardIcon(), falling back to a hardcoded per-index icon when empty",
      component: "components/HomeEditorialSections.tsx EditorialFeatureSection (<feature.icon data-icon=...>)",
      frontendSelector: '[data-testid="home-feature-attend-feature-feature0"] svg[data-icon]',
      expectedBehavior:
        "Migrated live this pass: npm run sanity:backfill-home-feature-icons populated all 8 feature items (4 " +
        "here + 4 on Host at RORUM) across both page-home and drafts.page-home, with the exact icon names " +
        "previously hardcoded — verified idempotent (a re-run dry-run reports 0 remaining) and pixel-identical " +
        "(committed EN visual baseline unchanged). Invalid/missing names still fall back safely to CircleEllipsis.",
      mutationStrategy: "icon-swap",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].actions[actionKey="cta"].label/.href/.linkType/.openInNewTab/.enabled',
      fieldPurpose: "Attend Events feature button — text and destination",
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> ctaAction, via resolveAction()",
      component: 'components/HomeEditorialSections.tsx EditorialFeatureSection (data-testid="home-feature-attend-cta")',
      frontendSelector: '[data-testid="home-feature-attend-cta"]',
      expectedBehavior: "Button text and href both follow Sanity; enabled=false renders no CTA link at all.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "editorialAttendEvents",
      sanityPath: 'sections[sectionKey=="editorialAttendEvents"].media[0].image/.alt',
      fieldPurpose: "Attend Events feature photo + alt text",
      fieldType: "image",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature() -> attendFeature.image/imageAlt",
      component: 'components/HomeEditorialSections.tsx EditorialFeatureSection (data-testid="home-feature-attend-media")',
      frontendSelector: '[data-testid="home-feature-attend-media"] (role="img")',
      expectedBehavior: "Background image + accessible name change to the edited asset/text once populated.",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "pending-approved-migration",
      notes:
        "Code wiring is correct and unconditional (already \"connected\" from the code's point of view) — " +
        "classified pending-approved-migration because production has 0 media items here, and an idempotent, " +
        "dry-run-only migration (scripts/backfill-home-fallback-images.ts) that would populate it with the exact " +
        "photo currently shown via code fallback has not been run live.",
    },

    {
      pageKey: "home",
      sectionKey: "editorialHostAtRorum",
      sanityPath: 'sections[sectionKey=="editorialHostAtRorum"].* (identical shape to editorialAttendEvents)',
      fieldPurpose: "Host at RORUM feature block — eyebrow/title/intro/description/features/icons/cta/media",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() resolveFeature(hostFeatureSection, fallback.hostFeature)",
      component: 'components/HomeEditorialSections.tsx EditorialFeatureSection (data-testid="home-feature-host", reversed)',
      frontendSelector: '[data-testid="home-feature-host"] and its -eyebrow/-intro/-description/-feature-*/-cta/-media children',
      expectedBehavior: "Identical connectivity to editorialAttendEvents above, field for field.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "pending-approved-migration",
      notes:
        "Collapsed into one entry to avoid duplicating ~6 near-identical rows — this classification reflects the " +
        "least-complete field in the group, not the whole group's state. Precisely: eyebrow/title/intro/" +
        "description/feature labels/cta text+href are `connected`; the 4 feature icons are now `connected` too " +
        "(migrated live this pass, same as editorialAttendEvents — see that entry above); the section's media " +
        "(photo) is still `pending-approved-migration` — production has 0 media items here and " +
        "scripts/backfill-home-fallback-images.ts has only been dry-run, not run live (see the image-migration " +
        "entry below and the Home report's image-alt-text analysis).",
    },

    // ---- servicesTeaser --------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "servicesTeaser",
      sanityPath: 'sections[sectionKey=="servicesTeaser"].label/.title',
      fieldPurpose: "Services section eyebrow + title",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() servicesLabel/servicesTitle",
      component: "components/HomeEditorialSections.tsx ServicesTeaserSection (SectionHeader)",
      frontendSelector: '[data-testid="home-services-label"], getByRole("heading", {level:2})',
      expectedBehavior: "Label/H2 text changes.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "servicesTeaser",
      sanityPath: 'sections[sectionKey=="servicesTeaser"].items[itemKey=~"catering|eventDecoration"].title/.text/.label/.href/.image',
      fieldPurpose: "2 service cards (Catering / Event decoration)",
      fieldType: "repeatable",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() services[] — title/text/label/href/image all read from Sanity",
      component: "components/HomeEditorialSections.tsx ServicesTeaserSection",
      frontendSelector: '[data-testid="home-service-catering"], [data-testid="home-service-event-decoration"]',
      expectedBehavior: "Card title/text/link-label/link-destination/image all change per item.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- communityTeaser -------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "communityTeaser",
      sanityPath: 'sections[sectionKey=="communityTeaser"].label/.title/.text',
      fieldPurpose: "Community teaser eyebrow/title/paragraph",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() communityLabel/communityTitle/communityText",
      component: "components/HomeEditorialSections.tsx CommunityTeaserSection",
      frontendSelector: '[data-testid="home-community-label"], getByRole("heading", {level:2}), [data-testid="home-community-text"]',
      expectedBehavior: "Label/H2/paragraph text change.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "communityTeaser",
      sanityPath: 'sections[sectionKey=="communityTeaser"].media[0].image',
      fieldPurpose: "Community teaser background photo",
      fieldType: "image",
      required: false,
      languages: [],
      querySource: QUERY,
      mapper: "getData() communityImageUrl",
      component: '[data-testid="home-community-teaser"] (style backgroundImage)',
      frontendSelector: '[data-testid="home-community-teaser"][style*=background-image]',
      expectedBehavior: "Background photo changes to the uploaded asset once populated.",
      mutationStrategy: "image-swap",
      editorVisibility: "visible",
      classification: "pending-approved-migration",
      notes: "Code wiring already unconditional; production has 0 media items — see scripts/backfill-home-fallback-images.ts (dry-run only).",
    },
    {
      pageKey: "home",
      sectionKey: "communityTeaser",
      sanityPath: 'sections[sectionKey=="communityTeaser"].items[itemKey=~"wecoda|workWithUs|volunteer"].label/.href',
      fieldPurpose: "3 community pill links",
      fieldType: "repeatable",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() communityLinks[] — label and href both read",
      component: '[data-testid="home-community-teaser"] a (pill links)',
      frontendSelector: 'getByRole("link") inside [data-testid="home-community-teaser"], by accessible name',
      expectedBehavior: "Pill text and destination change per item.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- closingCta --------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].label/.title/.text',
      fieldPurpose: 'Closing "Let\'s shape your idea together" eyebrow/title/paragraph',
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() closingEyebrow/closingTitle/closingText",
      component: 'components/ui.tsx CTASection (variant="final", data-testid="home-closing-cta")',
      frontendSelector: '[data-testid="home-closing-cta-eyebrow"], getByRole("heading",{level:2}), [data-testid="home-closing-cta-text"]',
      expectedBehavior: "Label/H2/paragraph change to the edited values.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].actions[actionKey="main"].label/.href/.linkType/.openInNewTab/.enabled',
      fieldPurpose: '"Let\'s talk" button — text and destination',
      fieldType: "i18nString",
      required: true,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() closingMainAction, via resolveAction()",
      component: '[data-testid="home-closing-cta-cta"]',
      frontendSelector: '[data-testid="home-closing-cta-cta"]',
      expectedBehavior: "Button text and href both follow Sanity; enabled=false renders no button at all.",
      mutationStrategy: "link-href",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].items[itemKey="faqQuestion"|"faqLabel"].title',
      fieldPurpose: "Inline FAQ prompt question + link label",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() closingFaqQuestion/closingFaqLabel",
      component: "components/FAQInlinePrompt.tsx (.faq-inline-prompt)",
      frontendSelector: ".faq-inline-prompt span (question), .faq-inline-prompt-link span (label)",
      expectedBehavior: "FAQ prompt question/link text change.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },
    {
      pageKey: "home",
      sectionKey: "closingCta",
      sanityPath: 'sections[sectionKey=="closingCta"].items[itemKey^="link"].label/.href',
      fieldPurpose: "4 suggested-path links (Events/Host/Catering/Decoration)",
      fieldType: "repeatable",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() closingLinks[] — label and href both read",
      component: '[aria-label="Suggested paths"] a',
      frontendSelector: '[aria-label="Suggested paths"] a, by accessible name',
      expectedBehavior: "Link text and destination change per item.",
      mutationStrategy: "localized-canary",
      editorVisibility: "visible",
      classification: "connected",
    },

    // ---- page-level SEO --------------------------------------------------
    {
      pageKey: "home",
      sectionKey: "seo",
      sanityPath: "seo.description",
      fieldPurpose: "Meta description for the Home page",
      fieldType: "i18nText",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "generateMetadata() -> getData().description",
      component: "app/[locale]/(site)/page.tsx generateMetadata() (<meta name=description>)",
      frontendSelector: 'head meta[name="description"]',
      expectedBehavior: "Meta description reflects the current page-home document's own SEO description, per locale, falling back to English then to the hardcoded default only when Sanity has nothing.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "Fixed this pass: generateMetadata() previously read `page?.seo?.description` from the obsolete, always-" +
        "null homePageQuery result instead of the current page-home document — see the Home Content Audit's " +
        "disconnected-field report for the original defect. Now reads newPage?.seo?.description. \"Connected\" " +
        "describes the code path, not the content: page-home's own seo.description is currently an empty string, " +
        "so every locale still renders the hardcoded fallback today — connected in code, not yet populated in Sanity.",
    },
    {
      pageKey: "home",
      sectionKey: "seo",
      sanityPath: "seo.title",
      fieldPurpose: "SEO title (<title> tag) for the Home page",
      fieldType: "i18nString",
      required: false,
      languages: ALL,
      querySource: QUERY,
      mapper: "getData() seoTitle -> generateMetadata()",
      component: "app/[locale]/(site)/page.tsx generateMetadata()",
      frontendSelector: "head > title",
      expectedBehavior:
        "Wired this pass (code-only, per explicit approval): reads newPage?.seo?.title, falling back to the " +
        "hardcoded default exactly like seo.description does. The `seo.title` schema field was NOT newly added — " +
        "it already existed on the shared `seo` object type (0 new Content Lake attributes; the path already " +
        "carries real values on 28 other documents in the dataset). Content on page-home is still empty as of " +
        "this change (population intentionally not approved yet), so <title> currently still renders the " +
        "hardcoded fallback for every locale — that is the correct, tested behavior of the empty-value branch, " +
        "not a wiring gap.",
      mutationStrategy: "not-mutation-tested",
      editorVisibility: "visible",
      classification: "connected",
      notes:
        "\"Connected\" here means the code path is correct and tested for both branches (see " +
        "tests/cms-home-contract.spec.ts's two SEO-title tests) — it does NOT mean an editor's title is currently " +
        "visible; production content for this field is still empty. Distinguish \"connected in code\" from " +
        "\"populated in Sanity\": this entry is the former, not (yet) the latter.",
    },
  ],
};
